### ISSUE TITLE
Error: 'across' is not an exported object from 'namespace:dplyr'

### ISSUE THREAD

**Issue by saptahash** [vincentarelbundock/modelsummary#114] opened 2020-08-19 13:59 UTC
I'm trying to run a pretty basic code to see if modelsummary would work

```
library(modelsummary)
library(tidyverse)

url <- 'https://vincentarelbundock.github.io/Rdatasets/csv/palmerpenguins/penguins.csv'
penguins <- read.csv(url)

modelsummary::datasummary(flipper_length_mm ~ mean, data = penguins)
```

I get an error saying `Error: 'across' is not an exported object from 'namespace:dplyr'`

I couldn't find a log for this error on any of the previous issues. Am I doing something wrong with the syntax or installation? 

Thanks!

**Comment by vincentarelbundock** [comment] 2020-08-19 15:02
Thanks a lot for the bug report. These are super useful!

I think the problem is that `modelsummary` requires version >=1.0.0 of `dplyr`, but I forgot to add this constraint in the package DESCRIPTION. As a result, you might have installed `modelsummary` with an old `dplyr` version, and `R` did not prompt you to update the package.

Could you try:

1. Update `dplyr` with `install.packages('dplyr')`
2. Install the new version of modelsummary from Github: `remotes::install_github('vincentarelbundock/modelsummary')`
3. Close your R session completely and start a fresh new one (sometimes RStudio needs a restart).
4. Try again.

I expect this to work. In the next CRAN release, I will specify the required version explicitly so people don't run into this issue.

**Comment by saptahash** [comment] 2020-08-19 15:38
Thanks a lot for this -- it did eventually work! 

The steps I had to go through were very similar to what you had suggested: 
1. Update `dplyr`
At this point, on installing the new version of `modelsummary` through `remotes`, I was prompted a range of package updates (~20 updates). If I click on update 'All', typically the update would fail because some packages aren't installed on my system (eg. `glue` or `htmltools`)
2. Install the missing package dependencies
3. Re-run updates on these packages when prompted by the `remotes::install_github('vincentarelbundock/modelsummary')`
4. Installation complete -> restart session -> works! 

I suspect that I should have had all dependencies installed, so that updates are prompted and correctly updated -- as opposed to using the previously installed `modelsummary`. 

Thanks for a prompt reply to this!

**Comment by vincentarelbundock** [comment] 2020-08-19 15:40
Excellent news!

I'll leave this issue open until I push a new version to CRAN with the required dependencies.

Thanks for using the package!

**Comment by vincentarelbundock** [comment] 2020-08-28 12:30
already implemented on Github, will be part of the CRAN release next week

**Closed by vincentarelbundock** 2020-08-28 12:30 UTC
Labels: bug
