### ISSUE TITLE
Slow modelsummary on simple feols from fixest objects (latest easystats)

### ISSUE THREAD

**Issue by astraetech** [vincentarelbundock/modelsummary#817] opened 2024-10-04 23:37 UTC
Hi Vincent,

I was wondering if you could look into a problem processing feols from fixest with modelsummary? All of my feols take a lot of time.  And the only thing i'm pulling out are the tstats. Here is the bench

```

bench::mark(modelsummary(est_list_1,  output = "flextable", estimate="{estimate}{stars}", fmt=3,
                            #shape = "cbind",
                            statistic = 'statistic', stars = c('*' = .1, '**' = .05, '***'=0.01),
                            gof_omit = 'DF|Deviance|R2 Adj.|AIC|BIC|R2 Within|R2 Pseudo|Log.Lik.',
                            coef_rename = coef_rename, rename=c("ret_mon_rf"="Ret"),
                            gof_map=gm,
                            add_rows=insert_row(est_list_1)
))
# A tibble: 1 × 13
  expression                         min median `itr/sec` mem_alloc `gc/sec` n_itr  n_gc total_time
  <bch:expr>                       <bch> <bch:>     <dbl> <bch:byt>    <dbl> <int> <dbl>   <bch:tm>
1 "modelsummary(est_list_1, outpu…   18s    18s    0.0556     381MB    0.389     1     7        18s
# ℹ 4 more variables: result <list>, memory <list>, time <list>, gc <list>
Warning message:
Some expressions had a GC in every iteration; so filtering is disabled. 
```

Unfortunately I can't attach my estimates list file due to privacy reasons. Can I send it to you?

Here are the versions:
```
> packageVersion("modelsummary")
[1] ‘2.2.0.1’
> packageVersion("easystats")
[1] ‘0.7.3.2’
> packageVersion("fixest")
[1] ‘0.12.1’
```

Thank you very much!

**Comment by vincentarelbundock** [comment] 2024-10-05 12:01
Can you read this and see what specific part of the workflow is slow? 

https://modelsummary.com/vignettes/modelsummary.html#how-can-i-speed-up-modelsummary

Also, try using the default output format rather than `flextable` to make sure this is not due to an external package.

**Comment by astraetech** [comment] 2024-10-06 19:58
Hi, 

So i read that link and ran some limited tests on est_list_1 a list of 9 model results all feols from fixest:

Just one model from the list

```
> bench::mark(performance::performance(est_list_1[[1]]))
# A tibble: 1 × 13
  expression    min median `itr/sec` mem_alloc `gc/sec` n_itr  n_gc total_time result     memory    
  <bch:expr> <bch:> <bch:>     <dbl> <bch:byt>    <dbl> <int> <dbl>   <bch:tm> <list>     <list>    
1 performan… 32.7ms 37.7ms      25.3    18.8MB        0    13     0      513ms <prfrmnc_> <Rprofmem>
# ℹ 2 more variables: time <list>, gc <list>
```

Another method - slower

```
> bench::mark(x <- parameters::parameters(est_list_1[[1]]))
# A tibble: 1 × 13
  expression    min median `itr/sec` mem_alloc `gc/sec` n_itr  n_gc total_time result     memory    
  <bch:expr>  <bch> <bch:>     <dbl> <bch:byt>    <dbl> <int> <dbl>   <bch:tm> <list>     <list>    
1 x <- param… 1.33s  1.33s     0.754    13.6MB        0     1     0      1.33s <prmtrs_m> <Rprofmem>
# ℹ 2 more variables: time <list>, gc <list>
```

Modelsummary on one model


```
> bench::mark(modelsummary(est_list_1[[1]], gof_map=NA))
# A tibble: 1 × 13
  expression           min median `itr/sec` mem_alloc `gc/sec` n_itr  n_gc total_time result        
  <bch:expr>         <bch> <bch:>     <dbl> <bch:byt>    <dbl> <int> <dbl>   <bch:tm> <list>        
1 modelsummary(est_… 1.41s  1.41s     0.710    13.5MB    0.710     1     1      1.41s <tinytabl[,2]>
# ℹ 3 more variables: memory <list>, time <list>, gc <list>
Warning message:
Some expressions had a GC in every iteration; so filtering is disabled. 
```



The whole list

```
> bench::mark(modelsummary(est_list_1, gof_map=NA))
# A tibble: 1 × 13
  expression          min median `itr/sec` mem_alloc `gc/sec` n_itr  n_gc total_time result         
  <bch:expr>        <bch> <bch:>     <dbl> <bch:byt>    <dbl> <int> <dbl>   <bch:tm> <list>         
1 modelsummary(est… 13.2s  13.2s    0.0759     148MB    0.532     1     7      13.2s <tinytabl[,10]>
# ℹ 3 more variables: memory <list>, time <list>, gc <list>
Warning message:
Some expressions had a GC in every iteration; so filtering is disabled.
```

With metrics specified


```
> bench::mark(modelsummary(est_list_1, gof_map=NA, metrics=c("R2"))
+ )
# A tibble: 1 × 13
  expression          min median `itr/sec` mem_alloc `gc/sec` n_itr  n_gc total_time result         
  <bch:expr>        <bch> <bch:>     <dbl> <bch:byt>    <dbl> <int> <dbl>   <bch:tm> <list>         
1 "modelsummary(es… 13.6s  13.6s    0.0737     150MB    0.516     1     7      13.6s <tinytabl[,10]>
# ℹ 3 more variables: memory <list>, time <list>, gc <list>
Warning message:
Some expressions had a GC in every iteration; so filtering is disabled. 
```

I can send you the model list in an .rda. This delay happens across all calls to modelsummary
 to render feols results which is atm 100% of my reg workflow.

Thank you again for your time!

**Comment by vincentarelbundock** [comment] 2024-10-06 20:03
Sure, you can email me the data and I'll take a look

**Comment by vincentarelbundock** [comment] 2024-11-06 22:08
Closing because not reproducible on my machine.

**Closed by vincentarelbundock** 2024-11-06 22:08 UTC
