### ISSUE TITLE
Combine multiple coefficients on one line

### ISSUE THREAD

**Issue by MarcoPortmann** [vincentarelbundock/modelsummary#738] opened 2024-04-03 10:38 UTC
Is there an easy way to summarize a set of coefficients and simply print a check mark or a "yes" in the table if a model contains one of the coefficients? I often shorten the output table when there are a large number of fixed effects and control variables, but the magnitude and significance of the effects are of little interest to the reader.

I had something like that in mind:
```r
m <- lm(hp ~ ., data = mtcars)
modelsummary(m, coef_map = list(cyl = "Cylinders", "gear" = "Gear",  "(qsec)|(mpg)" = "Control variables", "(vs)|(am)|(disp)" = "More control variables"))
```

The logic would be as follows: `coef_map` accepts regular expressions. If `coef_map = list(coef_raw = coef_pretty)` matches one `coef_raw` and one `coef_pretty`, then the estimated value is displayed; if several matches for `coef_raw` are found, then a check mark is displayed.

So far, I have used a custom function that generates a data.frame with one line and fills it with checkmarks if coefficients specified by the user are present in a model. I added this table with `attr(chk_tab, "position) <- row_above_gof` and `modelsummary(..., add_rows = chk_tab)`. All of this can be automated outside of `modelsummary`. But this requires that the number of coefficients to be printed  (`models`, `coef_map`, `coef_omit`) and the 'shape' argument must also be evaluated outside of  `modelsummary`.

**Comment by vincentarelbundock** [comment] 2024-04-03 11:27
Hi, thanks for the feature request.

I agree that this is an important and common use case. However, I'm not too keen on introducing yet another weird string-based syntax. We already support glue strings with curly braces `{}`, and I am afraid that inventing yet another string interpolation-style syntax would be confusing to users.

I'll think about whether there is a good user interface strategy to make this easier. In the meantime, I recommend you replace your `add_rows` strategy with a more robust and easy use of `glance_custom.classname`. See the example here:

https://modelsummary.com/vignettes/modelsummary.html#collapse-control-variables-into-an-indicator

**Comment by MarcoPortmann** [comment] 2024-04-03 12:42
I would argue that the proposed syntax is not very fancy, as it is just a change of coefficient names to a regular expression to be able to handle multiple coefficients at once. I would also be open to an additional argument instead of making `coef_map more complicated. However, I understand your hesitation to add more functions and twists to the user interface.

The `glance_custom.classname` strategy sounds intersting. If `...` from modelsummary was passed to `glance_custom.classname`, this would increase the flexiblity to pass the list of control variables from `modelsummary`. If I'm not mistaken `...` is not passed to  `glance_custom.classname`, right?

**Comment by vincentarelbundock** [comment] 2024-04-04 02:10
Right. `...` does not appear to be passed. What would be your use-case here? I'm asking because it seems pretty sensible to make it pass, just for added flexibility. But the problem is that this is a breaking change. Every single script which includes a `tidy_custom()` or `glance_custom()` method without `...` will raise an error.

I really want to avoid breaking change unless the change *really* makes a very big improvement in quality of life going forward.

**Comment by vincentarelbundock** [comment] 2024-04-04 02:58
One reason you can see me resisting a bit, is that this feels to me like
a niche solution to a niche (but cool) use-case. When I implement new
arguments or interfaces, I really try to make sure that they’ll solve
multiple (possibly unforseen) problems at once.

Would a `gof_function` argument be easier to use than the
`glance_custom` trick? Or is this basically the same?

``` r
library(modelsummary)

mod <- list(
  glm(am ~ hp + factor(cyl), data = mtcars, family = binomial),
  lm(mpg ~ hp + factor(cyl) + gear + qsec, data = mtcars)
)

fun <- function(x, ...) {
    if (all(c("gear", "qsec") %in% names(coef(x)))) {
        out <- data.frame(Controls = "✗")
    } else {
        out <- data.frame(Controls = "✓")
    }
    return(out)
}

modelsummary(mod, 
             gof_function = fun, 
             gof_map = c("nobs", "r.squared", "Controls"),
             coef_omit = "qsec|gear")

+--------------+---------+----------+
|              | (1)     | (2)      |
+==============+=========+==========+
| (Intercept)  | -2.029  | 33.178   |
+--------------+---------+----------+
|              | (1.604) | (13.713) |
+--------------+---------+----------+
| hp           | 0.038   | -0.057   |
+--------------+---------+----------+
|              | (0.019) | (0.018)  |
+--------------+---------+----------+
| factor(cyl)6 | -2.874  | -4.818   |
+--------------+---------+----------+
|              | (1.360) | (1.805)  |
+--------------+---------+----------+
| factor(cyl)8 | -8.644  | -4.037   |
+--------------+---------+----------+
|              | (3.423) | (3.585)  |
+--------------+---------+----------+
| Num.Obs.     | 32      | 32       |
+--------------+---------+----------+
| R2           |         | 0.812    |
+--------------+---------+----------+
| Controls     | ✓       | ✗        |
+--------------+---------+----------+ 
```

**Comment by vincentarelbundock** [comment] 2024-04-04 03:01
Or maybe something like this:

```r
fun = \(x) ifelse(all(c("qsec", "gear") %in% names(coef(x))), "X", "")
modelsummary(mod, gof_function = list("Controls" = fun))
```

**Comment by MarcoPortmann** [comment] 2024-04-05 13:36
> Right. `...` does not appear to be passed. What would be your use-case here? I'm asking because it seems pretty sensible to make it pass, just for added flexibility. But the problem is that this is a breaking change. Every single script which includes a `tidy_custom()` or `glance_custom()` method without `...` will raise an error.
> 
> I really want to avoid breaking change unless the change _really_ makes a very big improvement in quality of life going forward.

The approach using `glance_custom.classname` results in the same control variables being defined for all models with the same estimation method in a script that contains several model summaries (unless the `glance_custom?` function is overwritten between the `modelsummary` commands). This could have been avoided if `...` had allowed the passing of a variable list. However, I would not pursue this approach any further for the reasons you mentioned.

**Comment by MarcoPortmann** [comment] 2024-04-05 13:51
> Or maybe something like this:
> 
> ```r
> fun = \(x) ifelse(all(c("qsec", "gear") %in% names(coef(x))), "X", "")
> modelsummary(mod, gof_function = list("Controls" = fun))
> ```

Is something like this possible?

```r
modelsummary(mod, gof_function = list("Controls" = collapse_coefficients(coefs = c("var1", "var2")))
```
`collapse_coefficients` would basically correspond to your `fun` but extended with the argument `coefs` which would either accept a list of coefficient names or regular expressions and the function could be included in the modelsummary package. This would allow the user to provide any other custom function instead. I could deal and live with that. However, I think a function argument, that consists of a named list of functions is not very easy to understand for many users.

**Comment by vincentarelbundock** [comment] 2024-04-05 14:23
I'm not convinced that I want to introduce a new function just for this.

I am interested in this feature, but I have not yet seen or thought of a user interface that I love. Will keep thinking about it.

**Comment by MarcoPortmann** [comment] 2024-04-05 14:59
My preference order would be: (1) An extension of `coef_map` as suggested above, (2) a new argument like `coef_combinations`, (3) `gof_function` as you suggested. If I come up with something more elegant, I'll post it. I think reducing control variables and fixed effects is not a niche feature and could help many users.

**Comment by vincentarelbundock** [comment] 2024-04-21 00:30
FYI, I merged a `gof_function` argument and gave a detailed example of a very flexible approach to achieve what you want using that argument and a [function factory](https://en.wikipedia.org/wiki/Factory_(object-oriented_programming). I think it's pretty cool, relatively easy, and incredibly flexible.

https://modelsummary.com/vignettes/modelsummary.html#gof_function

Thanks again for the feature request.

**Closed by vincentarelbundock** 2024-04-21 00:30 UTC

**Comment by MarcoPortmann** [comment] 2024-04-22 20:04
That looks very cool. I will try it out in the next few days.

Just a thought: aren't the combined coefficients usually shown immediately after the individually reported coefficients, i.e. above the other GOF measures? Here is an example:
![image](https://github.com/vincentarelbundock/modelsummary/assets/7468121/eaf8547f-1980-49a3-83fa-43b8ce96084b)

**Comment by MarcoPortmann** [comment] 2024-05-26 12:36
I have now used gof_function for various purposes and generally find the feature very useful. This results in two pieces of feedback:

1. The feature is so useful that I often want to apply more than one function to the results. Would it be possible to have gof_function process a list of functions? Of course, I can also summarise the functions as a user as follows (disclaimer: I have not tested the function thoroughly):

```r
bind_gof_functions <- function(gof_functions)
{
  checkmate::assert_list(gof_functions, types = "function", min.len = 1)
  
  function(model) 
  return(do.call(cbind, args = lapply(gof_functions, \(x)do.call(x, args = list(model = model)))))
}  

modelsummary(models, gof_function = bind_gof_functions(list(fun1, fun2)))
```

But maybe it would be enough and help other users to integrate this function into modelsummary and test if the user passes a function or a list to `gof_function`.

2. A disadvantage of the `gof_function` approach for handling fixed effects is that it is not so elegantly possible to pass `models` with a pipe to `modelsummary` and define the fixed effects on the fly and without repetition, since fixed effects have to be passed to both the `gof_function` and the `coef_omit` argument. As an illustration with a slightly extended `check_controls` function based on your template:

```r
check_controls <- function(variables, yes = "✓", no = "", criterion = "any", controls_name = "Controls") {
  checkmate::assert_character(variables, min.len = 1)
  checkmate::assert_string(no)
  checkmate::assert_string(yes)
  checkmate::assert_character(controls_name, min.len = 1, max.len = 1)
  criterion <- match.arg(criterion, c("any", "all"))
  if (criterion == "any")
    crit_fun <- any else crit_fun <- all
                         
  reg <- paste0("^", paste(variables, collapse = "$|^"), "$")
  fun <- function(model) {
    est <- get_estimates(model)
    df <- if (do.call(crit_fun, list(variables %in% est$term))) yes else no
    df <- data.frame(df)
    colnames(df) <- controls_name
    return(df)
  }
  list("fun" = fun, "regex" = reg)
}

mod <- list(
  lm(wt ~ qsec, data = mtcars),
  lm(wt ~ qsec + hp + mpg, data = mtcars)
```

Either `check_controls` is defined and saved before calling model_summary:
```r
cc <- check_controls(c("hp", "mpg", "bla"), criterion = "all", controls_name = "Some controls")

mod %>% modelsummary(gof_function = cc$fun, 
                     coef_omit = cc$regex)
```

Or the function would have to be created twice:
```r
mod %>% modelsummary(gof_function = check_controls(c("hp", "mpg", "bla"), criterion = "any")$fun, 
                     coef_omit = check_controls(c("hp", "mpg", "bla"), criterion = "any")$regex)
```

I would find it handy if `modelsummary`  offered the option of specifying all arguments of the above `check_controls` function via a separate argument (e.g. `combined_coefs`) in addition to the more direct `gof_function` approach. Btw., if `gof_function` accepted a list of functions, all user input provided via `combined_coefs` could simply be appended internally to the `gof_functions`-list and to `coef_omit`.

I am of course aware that especially my second feedback is very specific, and understand if you don't want to further bloat the interface of modelsummary.

**Comment by vincentarelbundock** [comment] 2024-05-26 13:07
Honestly, I'm not sure I understand what you want to achieve. This all just sounds super complicated, and I bet there are easy ways to simplify your process tremendously. For instance, you could (1) write a function to check controls and add an attribute to the model objects themselves, (2) define a `gof_function()` to check the custom model attribute and act accordingly.

Pseudo-code:

```r
model_info <- function(model) {
 attr(model, "includes_mpg") <- "mpg" %in% all.vars(model)
 return(model)
}

gf <- function(model) {
   data.frame("Includes mpg" = isTRUE(attr(model, "includes_mpg"))
}

lapply(models, model_info) |>
  modelsummary(gof_function = gf)
```

**Comment by MarcoPortmann** [comment] 2024-05-26 21:28
I understand what your proposed code does, but it doesn't address my two concerns/potential feature suggestions.

First, I often find that it would be convenient to apply more than one `gof_function` to a model simultaneously because there are so many use cases (e.g: summarising coefficients in several groups (‘Controls I’, ‘Controls II’), displaying discrete effects, displaying selected coefficients in percent). As written, I can achieve this with the `bind_gof_functions` function shared above. I just thought it would be nice and also helpful for other users if the function `bind_gof_functions` shared above would be implemented directly in `modelsummary` such that the `gof_function` argument could directly accept a list of functions:
```r
modelsummary(models,
             gof_function = list(cc$fun, show_discrete_effect, just_another_function),
             coef_omit = cc$regex)
```


The second and actually independent point is that I would find it practical if, for combining coefficients, I didn't need to define a custom `check_controls` function and an R object (`cc` in the example) before calling `modelsummary`, and then pass it to two arguments (`gof_function = cc$fun` and `coef_omit = cc$regex`). I'm just saying it would be incredibly convenient if something like the following were possible without any additional user effort:
```r
mod %>%
  modelsummary(coef_collapse = list(c("hp", "mpg")))

mod %>%
  modelsummary(coef_collapse = list(list(c("hp", "mpg"), "any", "Controls I"),
                                    list(c("something", "else"), "any", "Controls II")
                                    ))
```

The link between the two features is as follows: If feature 1 (`gof_function` accepts a function or a list of functions) were implemented, feature 2 (`coef_collapse` argument) would likely be easy to implement: For each element *i* of `coef_collapse` (assuming that `coef_collapse` allows multiple coefficient groupings)  a corresponding `cc_goup<i>$fun` must be added to `gof_function` and `cc<i>$regex` must be added to `coef_omit`.

**Comment by vincentarelbundock** [comment] 2024-05-26 21:52
Why can't you wrap both functionalities inside a single function?

As stated above in this thread, I do not plan to add a coef_collapse argument for the moment.

**Comment by MarcoPortmann** [comment] 2024-05-26 22:22
Sure, I can combine multiple functions into one and I can combine coefficients without a coef_collapse argument. Both of my suggestions would, in my opinion, allow users to streamline their code and keep it more flexible, so I thought it was worth revisiting the discussion.

No problem, if the user interface of `modelsummary` remains stable as it is, I'm fine to adapt my scripts to it.

**Comment by vincentarelbundock** [comment] 2024-05-26 22:39
Got it.

Yeah, I think I understand better now (was on the move so couldn't read in detail). But my conclusion is that it's trivial to have several operations in a single function. And I really like the simplicity and generality of `gof_function`, so I'm going to leave things as is.

I really appreciate your enthusiasm and feature requests. I also know that it can be disappointing to hear "no", but in the end I have to make choices over interfaces that *I* like because I'm going to bear the burden of implementation, maintenance, documentation, and user support. Hope you understand.
