### ISSUE TITLE
Formatting fixest model is slow using current GitHub version

### ISSUE THREAD

**Issue by turbanisch** [vincentarelbundock/modelsummary#479] opened 2022-05-24 15:30 UTC
For some reason, displaying a `fixest` model is very slow (>1 min) with the current GitHub development version (0.10.0.9000). 

At first I was puzzled by the discrepancy between `fixest::etable()` and `modelsummary()` because both seem to use the `sandwich` package under the hood. Then I noticed that rendering is almost instantaneous with `modelsummary` version 0.10.0 from CRAN (used below). 

I am aware that the development version is meant to be experimental but felt this was worth pointing out to you in case an accidental change led to this slowdown. Feel free to close immediately if this is not the case ;)

``` r
library(fixest)
library(modelsummary)

# estimate model
mod_trade <- feols(log(Euros)~ log(dist_km) | Product + Destination + Origin, data = trade)

# view with fixest::etable()
etable(mod_trade, 
       vcov = list(~Product, ~Product + Destination))
#>                          mod_trade        mod_trade.1
#> Dependent Var.:         log(Euros)         log(Euros)
#>                                                      
#> log(dist_km)    -2.169*** (0.0769) -2.169*** (0.1474)
#> Fixed-Effects:  ------------------ ------------------
#> Product                        Yes                Yes
#> Destination                    Yes                Yes
#> Origin                         Yes                Yes
#> _______________ __________________ __________________
#> S.E.: Clustered        by: Product  by: Prod. & Dest.
#> Observations                38,325             38,325
#> R2                         0.70402            0.70402
#> Within R2                  0.21827            0.21827
#> ---
#> Signif. codes: 0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

# view with modelsummary()
modelsummary(mod_trade, 
             vcov = list(~Product, ~Product + Destination),
             output = "markdown")
```

|                 |   Model 1   |          Model 2          |
|:----------------|:-----------:|:-------------------------:|
| log(dist_km)    |   -2.169    |          -2.169           |
|                 |   (0.077)   |          (0.147)          |
| Num.Obs.        |    38325    |           38325           |
| R2              |    0.704    |           0.704           |
| R2 Adj.         |    0.704    |           0.704           |
| R2 Within       |    0.218    |           0.218           |
| R2 Pseudo       |             |                           |
| AIC             |  151665.5   |         151665.5          |
| BIC             |  152084.6   |         152084.6          |
| Log.Lik.        | -75783.728  |        -75783.728         |
| Std.Errors      | by: Product | by: Product & Destination |
| FE: Product     |      X      |             X             |
| FE: Destination |      X      |             X             |
| FE: Origin      |      X      |             X             |

<sup>Created on 2022-05-24 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

<details style="margin-bottom:10px;">
<summary>
Session info
</summary>

``` r
sessioninfo::session_info()
#> ─ Session info ───────────────────────────────────────────────────────────────
#>  setting  value
#>  version  R version 4.1.2 (2021-11-01)
#>  os       macOS Monterey 12.3.1
#>  system   aarch64, darwin20
#>  ui       X11
#>  language (EN)
#>  collate  en_US.UTF-8
#>  ctype    en_US.UTF-8
#>  tz       Europe/Berlin
#>  date     2022-05-24
#>  pandoc   2.17.1.1 @ /Applications/RStudio.app/Contents/MacOS/quarto/bin/ (via rmarkdown)
#> 
#> ─ Packages ───────────────────────────────────────────────────────────────────
#>  package      * version    date (UTC) lib source
#>  assertthat     0.2.1      2019-03-21 [1] CRAN (R 4.1.0)
#>  backports      1.4.1      2021-12-13 [1] CRAN (R 4.1.1)
#>  broom          0.8.0      2022-04-13 [1] CRAN (R 4.1.1)
#>  checkmate      2.1.0      2022-04-21 [1] CRAN (R 4.1.1)
#>  cli            3.3.0      2022-04-25 [1] CRAN (R 4.1.1)
#>  colorspace     2.0-3      2022-02-21 [1] CRAN (R 4.1.1)
#>  crayon         1.5.1      2022-03-26 [1] CRAN (R 4.1.1)
#>  DBI            1.1.2      2021-12-20 [1] CRAN (R 4.1.1)
#>  digest         0.6.29     2021-12-01 [1] CRAN (R 4.1.1)
#>  dplyr          1.0.9      2022-04-28 [1] CRAN (R 4.1.1)
#>  dreamerr       1.2.3      2020-12-05 [1] CRAN (R 4.1.0)
#>  ellipsis       0.3.2      2021-04-29 [1] CRAN (R 4.1.0)
#>  evaluate       0.15       2022-02-18 [1] CRAN (R 4.1.1)
#>  fansi          1.0.3      2022-03-24 [1] CRAN (R 4.1.1)
#>  fastmap        1.1.0      2021-01-25 [1] CRAN (R 4.1.0)
#>  fixest       * 0.10.5     2022-05-21 [1] https://fastverse.r-universe.dev (R 4.1.2)
#>  Formula        1.2-4      2020-10-16 [1] CRAN (R 4.1.0)
#>  fs             1.5.2      2021-12-08 [1] CRAN (R 4.1.1)
#>  generics       0.1.2      2022-01-31 [1] CRAN (R 4.1.1)
#>  glue           1.6.2      2022-02-24 [1] CRAN (R 4.1.1)
#>  highr          0.9        2021-04-16 [1] CRAN (R 4.1.0)
#>  htmltools      0.5.2      2021-08-25 [1] CRAN (R 4.1.1)
#>  httr           1.4.3      2022-05-04 [1] CRAN (R 4.1.1)
#>  kableExtra     1.3.4      2021-02-20 [1] CRAN (R 4.1.0)
#>  knitr          1.39       2022-04-26 [1] CRAN (R 4.1.1)
#>  lattice        0.20-45    2021-09-22 [1] CRAN (R 4.1.2)
#>  lifecycle      1.0.1      2021-09-24 [1] CRAN (R 4.1.1)
#>  lmtest         0.9-40     2022-03-21 [1] CRAN (R 4.1.1)
#>  magrittr       2.0.3      2022-03-30 [1] CRAN (R 4.1.1)
#>  modelsummary * 0.10.0     2022-04-14 [1] CRAN (R 4.1.1)
#>  munsell        0.5.0      2018-06-12 [1] CRAN (R 4.1.0)
#>  nlme           3.1-157    2022-03-25 [1] CRAN (R 4.1.1)
#>  numDeriv       2016.8-1.1 2019-06-06 [1] CRAN (R 4.1.0)
#>  pillar         1.7.0      2022-02-01 [1] CRAN (R 4.1.1)
#>  pkgconfig      2.0.3      2019-09-22 [1] CRAN (R 4.1.0)
#>  purrr          0.3.4      2020-04-17 [1] CRAN (R 4.1.0)
#>  R.cache        0.15.0     2021-04-30 [1] CRAN (R 4.1.0)
#>  R.methodsS3    1.8.1      2020-08-26 [1] CRAN (R 4.1.0)
#>  R.oo           1.24.0     2020-08-26 [1] CRAN (R 4.1.0)
#>  R.utils        2.11.0     2021-09-26 [1] CRAN (R 4.1.1)
#>  R6             2.5.1      2021-08-19 [1] CRAN (R 4.1.1)
#>  Rcpp           1.0.8.3    2022-03-17 [1] CRAN (R 4.1.1)
#>  reprex         2.0.1      2021-08-05 [1] CRAN (R 4.1.1)
#>  rlang          1.0.2      2022-03-04 [1] CRAN (R 4.1.1)
#>  rmarkdown      2.14       2022-04-25 [1] CRAN (R 4.1.1)
#>  rstudioapi     0.13       2020-11-12 [1] CRAN (R 4.1.0)
#>  rvest          1.0.2      2021-10-16 [1] CRAN (R 4.1.1)
#>  sandwich       3.0-1      2021-05-18 [1] CRAN (R 4.1.0)
#>  scales         1.2.0      2022-04-13 [1] CRAN (R 4.1.1)
#>  sessioninfo    1.2.2      2021-12-06 [1] CRAN (R 4.1.1)
#>  stringi        1.7.6      2021-11-29 [1] CRAN (R 4.1.1)
#>  stringr        1.4.0      2019-02-10 [1] CRAN (R 4.1.0)
#>  styler         1.7.0      2022-03-13 [1] CRAN (R 4.1.1)
#>  svglite        2.1.0      2022-02-03 [1] CRAN (R 4.1.1)
#>  systemfonts    1.0.4      2022-02-11 [1] CRAN (R 4.1.1)
#>  tables         0.9.6      2020-09-22 [1] CRAN (R 4.1.0)
#>  tibble         3.1.7      2022-05-03 [1] CRAN (R 4.1.1)
#>  tidyr          1.2.0      2022-02-01 [1] CRAN (R 4.1.1)
#>  tidyselect     1.1.2      2022-02-21 [1] CRAN (R 4.1.1)
#>  utf8           1.2.2      2021-07-24 [1] CRAN (R 4.1.0)
#>  vctrs          0.4.1      2022-04-13 [1] CRAN (R 4.1.1)
#>  viridisLite    0.4.0      2021-04-13 [1] CRAN (R 4.1.0)
#>  webshot        0.5.3      2022-04-14 [1] CRAN (R 4.1.1)
#>  withr          2.5.0      2022-03-03 [1] CRAN (R 4.1.1)
#>  xfun           0.31       2022-05-10 [1] CRAN (R 4.1.1)
#>  xml2           1.3.3      2021-11-30 [1] CRAN (R 4.1.1)
#>  yaml           2.3.5      2022-02-21 [1] CRAN (R 4.1.1)
#>  zoo            1.8-10     2022-04-15 [1] CRAN (R 4.1.1)
#> 
#>  [1] /Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/library
#> 
#> ──────────────────────────────────────────────────────────────────────────────
```

</details>

**Comment by turbanisch** [comment] 2022-05-24 15:44
I should also point out that I was using the development version (0.10.5) of `fixest` as well, so that's what might have caused the issue in the first place. Going back to CRAN versions for both packages seems to work best for now.

**Comment by vincentarelbundock** [comment] 2022-05-24 16:53
Thanks for the report!

The next version of `modelsummary` will use `performance` to extract results instead of `broom`. This comes with many benefits, but it looks like there was an upstream bug for fixest. Could you update to the devel version of both `performance` and `modelsummary` and try again?

https://github.com/easystats/performance

**Comment by turbanisch** [comment] 2022-05-25 09:23
Thanks for looking into it! With the development versions of all three packages (`fixest`, `modelsummary`, `performance`), output is lightning-fast again. I do get a message that methods have been overwritten but I assume this is inteded when working with `performance`. Very cool package by the way, I wasn't aware of it at all.

``` r
library(fixest)
library(modelsummary)

# estimate model
mod_trade <- feols(log(Euros)~ log(dist_km) | Product + Destination + Origin, data = trade)

# view with fixest::etable()
etable(mod_trade, 
       vcov = list(~Product, ~Product + Destination))
#>                          mod_trade        mod_trade.1
#> Dependent Var.:         log(Euros)         log(Euros)
#>                                                      
#> log(dist_km)    -2.169*** (0.0769) -2.169*** (0.1474)
#> Fixed-Effects:  ------------------ ------------------
#> Product                        Yes                Yes
#> Destination                    Yes                Yes
#> Origin                         Yes                Yes
#> _______________ __________________ __________________
#> S.E.: Clustered        by: Product  by: Prod. & Dest.
#> Observations                38,325             38,325
#> R2                         0.70402            0.70402
#> Within R2                  0.21827            0.21827
#> ---
#> Signif. codes: 0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

# view with modelsummary()
modelsummary(mod_trade, 
             vcov = list(~Product, ~Product + Destination),
             output = "markdown")
#> Registered S3 methods overwritten by 'effectsize':
#>   method              from      
#>   standardize.Surv    datawizard
#>   standardize.bcplm   datawizard
#>   standardize.clm2    datawizard
#>   standardize.default datawizard
#>   standardize.mediate datawizard
#>   standardize.wbgee   datawizard
#>   standardize.wbm     datawizard
```

|                 |   Model 1   |          Model 2          |
|:----------------|:-----------:|:-------------------------:|
| log(dist_km)    |   -2.169    |          -2.169           |
|                 |   (0.077)   |          (0.147)          |
| Num.Obs.        |    38325    |           38325           |
| R2              |    0.704    |           0.704           |
| R2 Adj.         |    0.704    |           0.704           |
| R2 Within       |    0.218    |           0.218           |
| R2 Within Adj.  |    0.218    |           0.218           |
| RMSE            |    1.75     |           1.75            |
| Std.Errors      | by: Product | by: Product & Destination |
| FE: Product     |      X      |             X             |
| FE: Destination |      X      |             X             |
| FE: Origin      |      X      |             X             |

<sup>Created on 2022-05-25 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

<details style="margin-bottom:10px;">
<summary>
Session info
</summary>

``` r
sessioninfo::session_info()
#> ─ Session info ───────────────────────────────────────────────────────────────
#>  setting  value
#>  version  R version 4.1.2 (2021-11-01)
#>  os       macOS Monterey 12.3.1
#>  system   aarch64, darwin20
#>  ui       X11
#>  language (EN)
#>  collate  en_US.UTF-8
#>  ctype    en_US.UTF-8
#>  tz       Europe/Berlin
#>  date     2022-05-25
#>  pandoc   2.17.1.1 @ /Applications/RStudio.app/Contents/MacOS/quarto/bin/ (via rmarkdown)
#> 
#> ─ Packages ───────────────────────────────────────────────────────────────────
#>  package      * version     date (UTC) lib source
#>  backports      1.4.1       2021-12-13 [1] CRAN (R 4.1.1)
#>  bayestestR     0.12.1      2022-05-02 [1] CRAN (R 4.1.1)
#>  checkmate      2.1.0       2022-04-21 [1] CRAN (R 4.1.1)
#>  cli            3.3.0       2022-04-25 [1] CRAN (R 4.1.1)
#>  codetools      0.2-18      2020-11-04 [1] CRAN (R 4.1.2)
#>  colorspace     2.0-3       2022-02-21 [1] CRAN (R 4.1.1)
#>  crayon         1.5.1       2022-03-26 [1] CRAN (R 4.1.1)
#>  datawizard     0.4.1.1     2022-05-21 [1] Github (easystats/datawizard@c9aad90)
#>  digest         0.6.29      2021-12-01 [1] CRAN (R 4.1.1)
#>  dreamerr       1.2.3       2020-12-05 [1] CRAN (R 4.1.0)
#>  effectsize     0.6.0.1     2022-01-26 [1] CRAN (R 4.1.1)
#>  ellipsis       0.3.2       2021-04-29 [1] CRAN (R 4.1.0)
#>  evaluate       0.15        2022-02-18 [1] CRAN (R 4.1.1)
#>  fansi          1.0.3       2022-03-24 [1] CRAN (R 4.1.1)
#>  fastmap        1.1.0       2021-01-25 [1] CRAN (R 4.1.0)
#>  fixest       * 0.10.5      2022-05-25 [1] https://fastverse.r-universe.dev (R 4.1.2)
#>  Formula        1.2-4       2020-10-16 [1] CRAN (R 4.1.0)
#>  fs             1.5.2       2021-12-08 [1] CRAN (R 4.1.1)
#>  future         1.25.0      2022-04-24 [1] CRAN (R 4.1.1)
#>  future.apply   1.9.0       2022-04-25 [1] CRAN (R 4.1.1)
#>  generics       0.1.2       2022-01-31 [1] CRAN (R 4.1.1)
#>  globals        0.15.0      2022-05-09 [1] CRAN (R 4.1.1)
#>  glue           1.6.2       2022-02-24 [1] CRAN (R 4.1.1)
#>  highr          0.9         2021-04-16 [1] CRAN (R 4.1.0)
#>  htmltools      0.5.2       2021-08-25 [1] CRAN (R 4.1.1)
#>  httr           1.4.3       2022-05-04 [1] CRAN (R 4.1.1)
#>  insight        0.17.1      2022-05-13 [1] CRAN (R 4.1.1)
#>  kableExtra     1.3.4       2021-02-20 [1] CRAN (R 4.1.0)
#>  knitr          1.39        2022-04-26 [1] CRAN (R 4.1.1)
#>  lattice        0.20-45     2021-09-22 [1] CRAN (R 4.1.2)
#>  lifecycle      1.0.1       2021-09-24 [1] CRAN (R 4.1.1)
#>  listenv        0.8.0       2019-12-05 [1] CRAN (R 4.1.0)
#>  lmtest         0.9-40      2022-03-21 [1] CRAN (R 4.1.1)
#>  magrittr       2.0.3       2022-03-30 [1] CRAN (R 4.1.1)
#>  modelsummary * 0.10.0.9000 2022-05-25 [1] Github (vincentarelbundock/modelsummary@1a2f257)
#>  munsell        0.5.0       2018-06-12 [1] CRAN (R 4.1.0)
#>  nlme           3.1-157     2022-03-25 [1] CRAN (R 4.1.1)
#>  numDeriv       2016.8-1.1  2019-06-06 [1] CRAN (R 4.1.0)
#>  parallelly     1.31.1      2022-04-22 [1] CRAN (R 4.1.1)
#>  parameters     0.18.0      2022-05-24 [1] CRAN (R 4.1.1)
#>  performance    0.9.0.6     2022-05-25 [1] https://easystats.r-universe.dev (R 4.1.3)
#>  pillar         1.7.0       2022-02-01 [1] CRAN (R 4.1.1)
#>  pkgconfig      2.0.3       2019-09-22 [1] CRAN (R 4.1.0)
#>  purrr          0.3.4       2020-04-17 [1] CRAN (R 4.1.0)
#>  R.cache        0.15.0      2021-04-30 [1] CRAN (R 4.1.0)
#>  R.methodsS3    1.8.1       2020-08-26 [1] CRAN (R 4.1.0)
#>  R.oo           1.24.0      2020-08-26 [1] CRAN (R 4.1.0)
#>  R.utils        2.11.0      2021-09-26 [1] CRAN (R 4.1.1)
#>  R6             2.5.1       2021-08-19 [1] CRAN (R 4.1.1)
#>  Rcpp           1.0.8.3     2022-03-17 [1] CRAN (R 4.1.1)
#>  reprex         2.0.1       2021-08-05 [1] CRAN (R 4.1.1)
#>  rlang          1.0.2       2022-03-04 [1] CRAN (R 4.1.1)
#>  rmarkdown      2.14        2022-04-25 [1] CRAN (R 4.1.1)
#>  rstudioapi     0.13        2020-11-12 [1] CRAN (R 4.1.0)
#>  rvest          1.0.2       2021-10-16 [1] CRAN (R 4.1.1)
#>  sandwich       3.0-1       2021-05-18 [1] CRAN (R 4.1.0)
#>  scales         1.2.0       2022-04-13 [1] CRAN (R 4.1.1)
#>  sessioninfo    1.2.2       2021-12-06 [1] CRAN (R 4.1.1)
#>  stringi        1.7.6       2021-11-29 [1] CRAN (R 4.1.1)
#>  stringr        1.4.0       2019-02-10 [1] CRAN (R 4.1.0)
#>  styler         1.7.0       2022-03-13 [1] CRAN (R 4.1.1)
#>  svglite        2.1.0       2022-02-03 [1] CRAN (R 4.1.1)
#>  systemfonts    1.0.4       2022-02-11 [1] CRAN (R 4.1.1)
#>  tables         0.9.6       2020-09-22 [1] CRAN (R 4.1.0)
#>  tibble         3.1.7       2022-05-03 [1] CRAN (R 4.1.1)
#>  utf8           1.2.2       2021-07-24 [1] CRAN (R 4.1.0)
#>  vctrs          0.4.1       2022-04-13 [1] CRAN (R 4.1.1)
#>  viridisLite    0.4.0       2021-04-13 [1] CRAN (R 4.1.0)
#>  webshot        0.5.3       2022-04-14 [1] CRAN (R 4.1.1)
#>  withr          2.5.0       2022-03-03 [1] CRAN (R 4.1.1)
#>  xfun           0.31        2022-05-10 [1] CRAN (R 4.1.1)
#>  xml2           1.3.3       2021-11-30 [1] CRAN (R 4.1.1)
#>  yaml           2.3.5       2022-02-21 [1] CRAN (R 4.1.1)
#>  zoo            1.8-10      2022-04-15 [1] CRAN (R 4.1.1)
#> 
#>  [1] /Library/Frameworks/R.framework/Versions/4.1-arm64/Resources/library
#> 
#> ──────────────────────────────────────────────────────────────────────────────
```

</details>

**Comment by vincentarelbundock** [comment] 2022-05-31 02:54
This is now fixed upstream, but it requires installing both the development versions of `performance` and `insight` packages.

https://github.com/easystats/insight
https://github.com/easystats/performance

**Comment by edwinhu** [comment] 2022-07-23 22:32
modelsummary is also very slow for me using `fixest` (and also for the `lfe` package).

I installed everything from Github:
```R
> packageVersion('fixest')
[1] ‘0.10.5’
> packageVersion('modelsummary')
[1] ‘1.0.2’
> packageVersion('performance')
[1] ‘0.9.1.2’
> packageVersion('insight')
[1] ‘0.18.0.2’
```

**Comment by vincentarelbundock** [comment] 2022-07-23 23:46
@edwinhu, could you supply a minimal working example with public data?

The `fixest` models from the vignette seem plenty fast to me…

``` r
library(modelsummary)
library(bench)
library(fixest)

library(fixest)
data(trade)
mod = fepois(Euros ~ log(dist_km) | Origin + Destination + Product + Year, trade)
bench::mark(
    modelsummary(mod, output = "data.frame"),
    modelsummary(mod, gof_map = NA, output = "data.frame"),
    check = FALSE
)
#> # A tibble: 2 × 6
#>   expression                                                  min   median `itr/sec` mem_alloc `gc/sec`
#>   <bch:expr>                                             <bch:tm> <bch:tm>     <dbl> <bch:byt>    <dbl>
#> 1 modelsummary(mod, output = "data.frame")                  265ms    265ms      3.78   26.92MB     3.78
#> 2 modelsummary(mod, gof_map = NA, output = "data.frame")    154ms    164ms      6.11    8.01MB     3.06

sessionInfo()
#> R version 4.2.1 (2022-06-23)
#> Platform: x86_64-pc-linux-gnu (64-bit)
#> Running under: Ubuntu 22.04 LTS
#> 
#> Matrix products: default
#> BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.10.0
#> LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.10.0
#> 
#> locale:
#>  [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8   
#>  [6] LC_MESSAGES=en_US.UTF-8    LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C               LC_TELEPHONE=C            
#> [11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices datasets  utils     methods   base     
#> 
#> other attached packages:
#> [1] rmarkdown_2.14     fixest_0.10.5      bench_1.1.2        modelsummary_1.0.2 nvimcom_0.9-131   
#> 
#> loaded via a namespace (and not attached):
#>  [1] sass_0.4.2          jsonlite_1.8.0      splines_4.2.1       R.utils_2.12.0      bslib_0.4.0         Formula_1.2-4       datawizard_0.4.1.9 
#>  [8] profmem_0.6.0       tables_0.9.6        yaml_2.3.5          bayestestR_0.12.1.1 globals_0.15.1      numDeriv_2016.8-1.1 pillar_1.8.0       
#> [15] backports_1.4.1     lattice_0.20-45     glue_1.6.2          digest_0.6.29       checkmate_2.1.0     sandwich_3.0-2      R.oo_1.25.0        
#> [22] htmltools_0.5.3     Matrix_1.4-1        pkgconfig_2.0.3     listenv_0.8.0       purrr_0.3.4         xtable_1.8-4        mvtnorm_1.1-3      
#> [29] emmeans_1.7.5       tibble_3.1.7        styler_1.7.0        generics_0.1.3      ellipsis_0.3.2      TH.data_1.1-1       cachem_1.0.6       
#> [36] withr_2.5.0         cli_3.3.0           survival_3.3-1      magrittr_2.0.3      effectsize_0.7.0    estimability_1.4    evaluate_0.15      
#> [43] R.methodsS3_1.8.2   fs_1.5.2            future_1.26.1       fansi_1.0.3         parallelly_1.32.0   R.cache_0.15.0      bspm_0.3.9         
#> [50] nlme_3.1-158        MASS_7.3-57         dreamerr_1.2.3      tools_4.2.1         lifecycle_1.0.1     multcomp_1.4-19     stringr_1.4.0      
#> [57] reprex_2.0.1        compiler_4.2.1      jquerylib_0.1.4     rlang_1.0.4         grid_4.2.1          parameters_0.18.1   codetools_0.2-18   
#> [64] R6_2.5.1            zoo_1.8-10          knitr_1.39          performance_0.9.1.1 fastmap_1.1.0       future.apply_1.9.0  utf8_1.2.2         
#> [71] insight_0.18.0.2    stringi_1.7.8       parallel_4.2.1      Rcpp_1.0.9          vctrs_0.4.1         xfun_0.31           coda_0.19-4
```

<sup>Created on 2022-07-23 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by edwinhu** [comment] 2022-07-24 01:59
I can't think of a suitable public dataset, but I think I figured out my problem. My dataset has 8mm rows and 100 columns. The modelsummary object is creating something with a mem_alloc of like 20+ GB. 

Using your example above it actually works very fast, even when I duplicate the data 100x to get 3mm rows. So it probably has something to do with all of the columns. When I run my fixest regression and only keep the columns I need (e.g., one depvar and one indvar for testing) it runs very fast.

Is there some way to reduce the memory footprint of the modelsummary function other than manually selecting the columns that are actually used in the model?

**Comment by vincentarelbundock** [comment] 2022-07-24 02:17
Thanks a lot for diving in @edwinhu, this is *super* useful. Could you try something weird? 

Add the `fmt = "%.3f"` argument to your `modelsummary()` call.

I just tried to profile and see that a *ton* of memory is wasted in the `format()` function, and I want to make sure that something weird is not happening on my local machine. `fmt="%.3f"` will pass rounding to `sprintf()` instead.

**Comment by edwinhu** [comment] 2022-07-24 02:22
Doesn't seem to be a problem on my machine.

```R
mod = fepois(Euros ~ log(dist_km) | Origin + Destination + Product + Year, trade)
b<-bench::mark(
    modelsummary(mod, output = "data.frame", fmt = "%.3f"),
    modelsummary(mod, output = "data.frame"),
    modelsummary(mod, gof_map = NA, output = "data.frame"),
    check = FALSE
)
b$mem_alloc
26.88MB 26.88MB 7.99MB
```

Perhaps my problem could be solved using `model.frame` or something internally rather than storing a copy of the full dataset that is passed to `fixest`?

**Comment by vincentarelbundock** [comment] 2022-07-24 02:27
Sorry, I wasn't clear: Does your big model with the big dataset run faster when you use `fmt="%.3f"`?

Unfortunately, `model.frame()` doesn't seem to work with `fixest` objects, and that package is a bit idiosyncratic in that, unlike `lm()` or `glm()`, it does not store the original data (or model frame) in the object it produces. See here for a recent discussion of related problems:

https://github.com/lrberge/fixest/issues/340

**Comment by edwinhu** [comment] 2022-07-24 02:39
I see. From the link you posted I think a wrapper function to that creates a `model.frame` and then calls `fixest` should work for what I am trying to do (no loops).

Using `fmt="%.3f"` seems to give me the same performance (slow, big memory usage):
```R
b$mem_alloc
27.5GB

b$total_time
2.22m
```

**Comment by vincentarelbundock** [comment] 2022-07-24 02:44
Thanks for testing.

Yeah, a wrapper function should work for end-users, but I don't see a clear pathway for me to make this better, unfortunately...

**Comment by edwinhu** [comment] 2022-07-25 16:12
This is awesome. I just tested it out with my data and it took the compute time from 2+ min to a few seconds.

**Closed** 2022-07-25 16:17 UTC
Labels: bug
