### ISSUE TITLE
Loading `modelsummary` causes `knitr::kable` outputs being with weird format

### ISSUE THREAD

**Issue by iago-pssjd** [vincentarelbundock/modelsummary#256] opened 2021-04-07 16:17 UTC
I ask if `modelsummary` does some change in the options of `knitr::kable`, because in an `Rmd` document, when I use `kable` before any use of the function `modelsummary` it prints the table in the usual way, but later it is printed unformatted (when I knitr to an html document). I am using `results='asis'` in chunks and `modelsummary` with `output = "markdown"`. Below, the reprex:

More specifically, the output of the first `kable(mtcars)` is a markdown table, but the output of the second `kable(mtcars)` is the same table but in html.
``` r
kable(mtcars)
```

|                     |  mpg | cyl |  disp |  hp | drat |    wt |  qsec |  vs |  am | gear | carb |
|:--------------------|-----:|----:|------:|----:|-----:|------:|------:|----:|----:|-----:|-----:|
| Mazda RX4           | 21.0 |   6 | 160.0 | 110 | 3.90 | 2.620 | 16.46 |   0 |   1 |    4 |    4 |
| Mazda RX4 Wag       | 21.0 |   6 | 160.0 | 110 | 3.90 | 2.875 | 17.02 |   0 |   1 |    4 |    4 |
| Datsun 710          | 22.8 |   4 | 108.0 |  93 | 3.85 | 2.320 | 18.61 |   1 |   1 |    4 |    1 |
| Hornet 4 Drive      | 21.4 |   6 | 258.0 | 110 | 3.08 | 3.215 | 19.44 |   1 |   0 |    3 |    1 |
| Hornet Sportabout   | 18.7 |   8 | 360.0 | 175 | 3.15 | 3.440 | 17.02 |   0 |   0 |    3 |    2 |
| Valiant             | 18.1 |   6 | 225.0 | 105 | 2.76 | 3.460 | 20.22 |   1 |   0 |    3 |    1 |
| Duster 360          | 14.3 |   8 | 360.0 | 245 | 3.21 | 3.570 | 15.84 |   0 |   0 |    3 |    4 |
| Merc 240D           | 24.4 |   4 | 146.7 |  62 | 3.69 | 3.190 | 20.00 |   1 |   0 |    4 |    2 |
| Merc 230            | 22.8 |   4 | 140.8 |  95 | 3.92 | 3.150 | 22.90 |   1 |   0 |    4 |    2 |
| Merc 280            | 19.2 |   6 | 167.6 | 123 | 3.92 | 3.440 | 18.30 |   1 |   0 |    4 |    4 |
| Merc 280C           | 17.8 |   6 | 167.6 | 123 | 3.92 | 3.440 | 18.90 |   1 |   0 |    4 |    4 |
| Merc 450SE          | 16.4 |   8 | 275.8 | 180 | 3.07 | 4.070 | 17.40 |   0 |   0 |    3 |    3 |
| Merc 450SL          | 17.3 |   8 | 275.8 | 180 | 3.07 | 3.730 | 17.60 |   0 |   0 |    3 |    3 |
| Merc 450SLC         | 15.2 |   8 | 275.8 | 180 | 3.07 | 3.780 | 18.00 |   0 |   0 |    3 |    3 |
| Cadillac Fleetwood  | 10.4 |   8 | 472.0 | 205 | 2.93 | 5.250 | 17.98 |   0 |   0 |    3 |    4 |
| Lincoln Continental | 10.4 |   8 | 460.0 | 215 | 3.00 | 5.424 | 17.82 |   0 |   0 |    3 |    4 |
| Chrysler Imperial   | 14.7 |   8 | 440.0 | 230 | 3.23 | 5.345 | 17.42 |   0 |   0 |    3 |    4 |
| Fiat 128            | 32.4 |   4 |  78.7 |  66 | 4.08 | 2.200 | 19.47 |   1 |   1 |    4 |    1 |
| Honda Civic         | 30.4 |   4 |  75.7 |  52 | 4.93 | 1.615 | 18.52 |   1 |   1 |    4 |    2 |
| Toyota Corolla      | 33.9 |   4 |  71.1 |  65 | 4.22 | 1.835 | 19.90 |   1 |   1 |    4 |    1 |
| Toyota Corona       | 21.5 |   4 | 120.1 |  97 | 3.70 | 2.465 | 20.01 |   1 |   0 |    3 |    1 |
| Dodge Challenger    | 15.5 |   8 | 318.0 | 150 | 2.76 | 3.520 | 16.87 |   0 |   0 |    3 |    2 |
| AMC Javelin         | 15.2 |   8 | 304.0 | 150 | 3.15 | 3.435 | 17.30 |   0 |   0 |    3 |    2 |
| Camaro Z28          | 13.3 |   8 | 350.0 | 245 | 3.73 | 3.840 | 15.41 |   0 |   0 |    3 |    4 |
| Pontiac Firebird    | 19.2 |   8 | 400.0 | 175 | 3.08 | 3.845 | 17.05 |   0 |   0 |    3 |    2 |
| Fiat X1-9           | 27.3 |   4 |  79.0 |  66 | 4.08 | 1.935 | 18.90 |   1 |   1 |    4 |    1 |
| Porsche 914-2       | 26.0 |   4 | 120.3 |  91 | 4.43 | 2.140 | 16.70 |   0 |   1 |    5 |    2 |
| Lotus Europa        | 30.4 |   4 |  95.1 | 113 | 3.77 | 1.513 | 16.90 |   1 |   1 |    5 |    2 |
| Ford Pantera L      | 15.8 |   8 | 351.0 | 264 | 4.22 | 3.170 | 14.50 |   0 |   1 |    5 |    4 |
| Ferrari Dino        | 19.7 |   6 | 145.0 | 175 | 3.62 | 2.770 | 15.50 |   0 |   1 |    5 |    6 |
| Maserati Bora       | 15.0 |   8 | 301.0 | 335 | 3.54 | 3.570 | 14.60 |   0 |   1 |    5 |    8 |
| Volvo 142E          | 21.4 |   4 | 121.0 | 109 | 4.11 | 2.780 | 18.60 |   1 |   1 |    4 |    2 |

``` r
data(trees)
models <- list()
models[['Bivariate']] <- lm(Girth ~ Height, data = trees)
models[['Multivariate']] <- lm(Girth ~ Height + Volume, data = trees)

# simple table
modelsummary(models, output = 'markdown')
```

|             | Bivariate | Multivariate |
|:------------|:---------:|:------------:|
| (Intercept) |  -6.188   |    10.816    |
|             |  (5.960)  |   (1.973)    |
| Height      |   0.256   |    -0.045    |
|             |  (0.078)  |   (0.028)    |
| Volume      |           |    0.195     |
|             |           |   (0.011)    |
| Num.Obs.    |    31     |      31      |
| R2          |   0.270   |    0.941     |
| R2 Adj.     |   0.244   |    0.937     |
| AIC         |   154.1   |     78.2     |
| BIC         |   158.4   |     84.0     |
| Log.Lik.    |  -74.061  |   -35.116    |
| F           |  10.707   |   222.471    |

``` r
kable(mtcars)
```

<table>
<thead>
<tr>
<th style="text-align:left;">
</th>
<th style="text-align:right;">
mpg
</th>
<th style="text-align:right;">
cyl
</th>
<th style="text-align:right;">
disp
</th>
<th style="text-align:right;">
hp
</th>
<th style="text-align:right;">
drat
</th>
<th style="text-align:right;">
wt
</th>
<th style="text-align:right;">
qsec
</th>
<th style="text-align:right;">
vs
</th>
<th style="text-align:right;">
am
</th>
<th style="text-align:right;">
gear
</th>
<th style="text-align:right;">
carb
</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:left;">
Mazda RX4
</td>
<td style="text-align:right;">
21.0
</td>
<td style="text-align:right;">
6
</td>
<td style="text-align:right;">
160.0
</td>
<td style="text-align:right;">
110
</td>
<td style="text-align:right;">
3.90
</td>
<td style="text-align:right;">
2.620
</td>
<td style="text-align:right;">
16.46
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
4
</td>
<td style="text-align:right;">
4
</td>
</tr>
<tr>
<td style="text-align:left;">
Mazda RX4 Wag
</td>
<td style="text-align:right;">
21.0
</td>
<td style="text-align:right;">
6
</td>
<td style="text-align:right;">
160.0
</td>
<td style="text-align:right;">
110
</td>
<td style="text-align:right;">
3.90
</td>
<td style="text-align:right;">
2.875
</td>
<td style="text-align:right;">
17.02
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
4
</td>
<td style="text-align:right;">
4
</td>
</tr>
<tr>
<td style="text-align:left;">
Datsun 710
</td>
<td style="text-align:right;">
22.8
</td>
<td style="text-align:right;">
4
</td>
<td style="text-align:right;">
108.0
</td>
<td style="text-align:right;">
93
</td>
<td style="text-align:right;">
3.85
</td>
<td style="text-align:right;">
2.320
</td>
<td style="text-align:right;">
18.61
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
4
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
Hornet 4 Drive
</td>
<td style="text-align:right;">
21.4
</td>
<td style="text-align:right;">
6
</td>
<td style="text-align:right;">
258.0
</td>
<td style="text-align:right;">
110
</td>
<td style="text-align:right;">
3.08
</td>
<td style="text-align:right;">
3.215
</td>
<td style="text-align:right;">
19.44
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
Hornet Sportabout
</td>
<td style="text-align:right;">
18.7
</td>
<td style="text-align:right;">
8
</td>
<td style="text-align:right;">
360.0
</td>
<td style="text-align:right;">
175
</td>
<td style="text-align:right;">
3.15
</td>
<td style="text-align:right;">
3.440
</td>
<td style="text-align:right;">
17.02
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
2
</td>
</tr>
<tr>
<td style="text-align:left;">
Valiant
</td>
<td style="text-align:right;">
18.1
</td>
<td style="text-align:right;">
6
</td>
<td style="text-align:right;">
225.0
</td>
<td style="text-align:right;">
105
</td>
<td style="text-align:right;">
2.76
</td>
<td style="text-align:right;">
3.460
</td>
<td style="text-align:right;">
20.22
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
Duster 360
</td>
<td style="text-align:right;">
14.3
</td>
<td style="text-align:right;">
8
</td>
<td style="text-align:right;">
360.0
</td>
<td style="text-align:right;">
245
</td>
<td style="text-align:right;">
3.21
</td>
<td style="text-align:right;">
3.570
</td>
<td style="text-align:right;">
15.84
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
4
</td>
</tr>
<tr>
<td style="text-align:left;">
Merc 240D
</td>
<td style="text-align:right;">
24.4
</td>
<td style="text-align:right;">
4
</td>
<td style="text-align:right;">
146.7
</td>
<td style="text-align:right;">
62
</td>
<td style="text-align:right;">
3.69
</td>
<td style="text-align:right;">
3.190
</td>
<td style="text-align:right;">
20.00
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
4
</td>
<td style="text-align:right;">
2
</td>
</tr>
<tr>
<td style="text-align:left;">
Merc 230
</td>
<td style="text-align:right;">
22.8
</td>
<td style="text-align:right;">
4
</td>
<td style="text-align:right;">
140.8
</td>
<td style="text-align:right;">
95
</td>
<td style="text-align:right;">
3.92
</td>
<td style="text-align:right;">
3.150
</td>
<td style="text-align:right;">
22.90
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
4
</td>
<td style="text-align:right;">
2
</td>
</tr>
<tr>
<td style="text-align:left;">
Merc 280
</td>
<td style="text-align:right;">
19.2
</td>
<td style="text-align:right;">
6
</td>
<td style="text-align:right;">
167.6
</td>
<td style="text-align:right;">
123
</td>
<td style="text-align:right;">
3.92
</td>
<td style="text-align:right;">
3.440
</td>
<td style="text-align:right;">
18.30
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
4
</td>
<td style="text-align:right;">
4
</td>
</tr>
<tr>
<td style="text-align:left;">
Merc 280C
</td>
<td style="text-align:right;">
17.8
</td>
<td style="text-align:right;">
6
</td>
<td style="text-align:right;">
167.6
</td>
<td style="text-align:right;">
123
</td>
<td style="text-align:right;">
3.92
</td>
<td style="text-align:right;">
3.440
</td>
<td style="text-align:right;">
18.90
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
4
</td>
<td style="text-align:right;">
4
</td>
</tr>
<tr>
<td style="text-align:left;">
Merc 450SE
</td>
<td style="text-align:right;">
16.4
</td>
<td style="text-align:right;">
8
</td>
<td style="text-align:right;">
275.8
</td>
<td style="text-align:right;">
180
</td>
<td style="text-align:right;">
3.07
</td>
<td style="text-align:right;">
4.070
</td>
<td style="text-align:right;">
17.40
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
3
</td>
</tr>
<tr>
<td style="text-align:left;">
Merc 450SL
</td>
<td style="text-align:right;">
17.3
</td>
<td style="text-align:right;">
8
</td>
<td style="text-align:right;">
275.8
</td>
<td style="text-align:right;">
180
</td>
<td style="text-align:right;">
3.07
</td>
<td style="text-align:right;">
3.730
</td>
<td style="text-align:right;">
17.60
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
3
</td>
</tr>
<tr>
<td style="text-align:left;">
Merc 450SLC
</td>
<td style="text-align:right;">
15.2
</td>
<td style="text-align:right;">
8
</td>
<td style="text-align:right;">
275.8
</td>
<td style="text-align:right;">
180
</td>
<td style="text-align:right;">
3.07
</td>
<td style="text-align:right;">
3.780
</td>
<td style="text-align:right;">
18.00
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
3
</td>
</tr>
<tr>
<td style="text-align:left;">
Cadillac Fleetwood
</td>
<td style="text-align:right;">
10.4
</td>
<td style="text-align:right;">
8
</td>
<td style="text-align:right;">
472.0
</td>
<td style="text-align:right;">
205
</td>
<td style="text-align:right;">
2.93
</td>
<td style="text-align:right;">
5.250
</td>
<td style="text-align:right;">
17.98
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
4
</td>
</tr>
<tr>
<td style="text-align:left;">
Lincoln Continental
</td>
<td style="text-align:right;">
10.4
</td>
<td style="text-align:right;">
8
</td>
<td style="text-align:right;">
460.0
</td>
<td style="text-align:right;">
215
</td>
<td style="text-align:right;">
3.00
</td>
<td style="text-align:right;">
5.424
</td>
<td style="text-align:right;">
17.82
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
4
</td>
</tr>
<tr>
<td style="text-align:left;">
Chrysler Imperial
</td>
<td style="text-align:right;">
14.7
</td>
<td style="text-align:right;">
8
</td>
<td style="text-align:right;">
440.0
</td>
<td style="text-align:right;">
230
</td>
<td style="text-align:right;">
3.23
</td>
<td style="text-align:right;">
5.345
</td>
<td style="text-align:right;">
17.42
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
4
</td>
</tr>
<tr>
<td style="text-align:left;">
Fiat 128
</td>
<td style="text-align:right;">
32.4
</td>
<td style="text-align:right;">
4
</td>
<td style="text-align:right;">
78.7
</td>
<td style="text-align:right;">
66
</td>
<td style="text-align:right;">
4.08
</td>
<td style="text-align:right;">
2.200
</td>
<td style="text-align:right;">
19.47
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
4
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
Honda Civic
</td>
<td style="text-align:right;">
30.4
</td>
<td style="text-align:right;">
4
</td>
<td style="text-align:right;">
75.7
</td>
<td style="text-align:right;">
52
</td>
<td style="text-align:right;">
4.93
</td>
<td style="text-align:right;">
1.615
</td>
<td style="text-align:right;">
18.52
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
4
</td>
<td style="text-align:right;">
2
</td>
</tr>
<tr>
<td style="text-align:left;">
Toyota Corolla
</td>
<td style="text-align:right;">
33.9
</td>
<td style="text-align:right;">
4
</td>
<td style="text-align:right;">
71.1
</td>
<td style="text-align:right;">
65
</td>
<td style="text-align:right;">
4.22
</td>
<td style="text-align:right;">
1.835
</td>
<td style="text-align:right;">
19.90
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
4
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
Toyota Corona
</td>
<td style="text-align:right;">
21.5
</td>
<td style="text-align:right;">
4
</td>
<td style="text-align:right;">
120.1
</td>
<td style="text-align:right;">
97
</td>
<td style="text-align:right;">
3.70
</td>
<td style="text-align:right;">
2.465
</td>
<td style="text-align:right;">
20.01
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
Dodge Challenger
</td>
<td style="text-align:right;">
15.5
</td>
<td style="text-align:right;">
8
</td>
<td style="text-align:right;">
318.0
</td>
<td style="text-align:right;">
150
</td>
<td style="text-align:right;">
2.76
</td>
<td style="text-align:right;">
3.520
</td>
<td style="text-align:right;">
16.87
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
2
</td>
</tr>
<tr>
<td style="text-align:left;">
AMC Javelin
</td>
<td style="text-align:right;">
15.2
</td>
<td style="text-align:right;">
8
</td>
<td style="text-align:right;">
304.0
</td>
<td style="text-align:right;">
150
</td>
<td style="text-align:right;">
3.15
</td>
<td style="text-align:right;">
3.435
</td>
<td style="text-align:right;">
17.30
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
2
</td>
</tr>
<tr>
<td style="text-align:left;">
Camaro Z28
</td>
<td style="text-align:right;">
13.3
</td>
<td style="text-align:right;">
8
</td>
<td style="text-align:right;">
350.0
</td>
<td style="text-align:right;">
245
</td>
<td style="text-align:right;">
3.73
</td>
<td style="text-align:right;">
3.840
</td>
<td style="text-align:right;">
15.41
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
4
</td>
</tr>
<tr>
<td style="text-align:left;">
Pontiac Firebird
</td>
<td style="text-align:right;">
19.2
</td>
<td style="text-align:right;">
8
</td>
<td style="text-align:right;">
400.0
</td>
<td style="text-align:right;">
175
</td>
<td style="text-align:right;">
3.08
</td>
<td style="text-align:right;">
3.845
</td>
<td style="text-align:right;">
17.05
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
3
</td>
<td style="text-align:right;">
2
</td>
</tr>
<tr>
<td style="text-align:left;">
Fiat X1-9
</td>
<td style="text-align:right;">
27.3
</td>
<td style="text-align:right;">
4
</td>
<td style="text-align:right;">
79.0
</td>
<td style="text-align:right;">
66
</td>
<td style="text-align:right;">
4.08
</td>
<td style="text-align:right;">
1.935
</td>
<td style="text-align:right;">
18.90
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
4
</td>
<td style="text-align:right;">
1
</td>
</tr>
<tr>
<td style="text-align:left;">
Porsche 914-2
</td>
<td style="text-align:right;">
26.0
</td>
<td style="text-align:right;">
4
</td>
<td style="text-align:right;">
120.3
</td>
<td style="text-align:right;">
91
</td>
<td style="text-align:right;">
4.43
</td>
<td style="text-align:right;">
2.140
</td>
<td style="text-align:right;">
16.70
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
5
</td>
<td style="text-align:right;">
2
</td>
</tr>
<tr>
<td style="text-align:left;">
Lotus Europa
</td>
<td style="text-align:right;">
30.4
</td>
<td style="text-align:right;">
4
</td>
<td style="text-align:right;">
95.1
</td>
<td style="text-align:right;">
113
</td>
<td style="text-align:right;">
3.77
</td>
<td style="text-align:right;">
1.513
</td>
<td style="text-align:right;">
16.90
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
5
</td>
<td style="text-align:right;">
2
</td>
</tr>
<tr>
<td style="text-align:left;">
Ford Pantera L
</td>
<td style="text-align:right;">
15.8
</td>
<td style="text-align:right;">
8
</td>
<td style="text-align:right;">
351.0
</td>
<td style="text-align:right;">
264
</td>
<td style="text-align:right;">
4.22
</td>
<td style="text-align:right;">
3.170
</td>
<td style="text-align:right;">
14.50
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
5
</td>
<td style="text-align:right;">
4
</td>
</tr>
<tr>
<td style="text-align:left;">
Ferrari Dino
</td>
<td style="text-align:right;">
19.7
</td>
<td style="text-align:right;">
6
</td>
<td style="text-align:right;">
145.0
</td>
<td style="text-align:right;">
175
</td>
<td style="text-align:right;">
3.62
</td>
<td style="text-align:right;">
2.770
</td>
<td style="text-align:right;">
15.50
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
5
</td>
<td style="text-align:right;">
6
</td>
</tr>
<tr>
<td style="text-align:left;">
Maserati Bora
</td>
<td style="text-align:right;">
15.0
</td>
<td style="text-align:right;">
8
</td>
<td style="text-align:right;">
301.0
</td>
<td style="text-align:right;">
335
</td>
<td style="text-align:right;">
3.54
</td>
<td style="text-align:right;">
3.570
</td>
<td style="text-align:right;">
14.60
</td>
<td style="text-align:right;">
0
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
5
</td>
<td style="text-align:right;">
8
</td>
</tr>
<tr>
<td style="text-align:left;">
Volvo 142E
</td>
<td style="text-align:right;">
21.4
</td>
<td style="text-align:right;">
4
</td>
<td style="text-align:right;">
121.0
</td>
<td style="text-align:right;">
109
</td>
<td style="text-align:right;">
4.11
</td>
<td style="text-align:right;">
2.780
</td>
<td style="text-align:right;">
18.60
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
1
</td>
<td style="text-align:right;">
4
</td>
<td style="text-align:right;">
2
</td>
</tr>
</tbody>
</table>

<sup>Created on 2021-04-07 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by vincentarelbundock** [comment] 2021-04-07 16:32
Thanks for the report. No, `modelsummary` does not make any change to the default options of `kable`. However, it looks like `kableExtra` *does* make changes to the print method. `kableExtra` is the default backend, but this example shows that if you use a different backend (e.g., `gt`), then `modelsummary` won't change your `kable` output:

````
---
output: html_document
---

```{r}
library(knitr)
kable(head(mtcars))
```

```{r}
library(modelsummary)
mod = lm(hp ~ mpg, data = mtcars)
modelsummary(mod, output = "gt")
```

```{r}
kable(head(mtcars))
```
````

In case you want to search for related issues (and potentially report this) on the `kableExtra` repository, here is a Minimal Working Example that shows that `kableExtra` changes the default print method for `kable`:

````
---
output: html_document
---

```{r}
library(knitr)
kable(head(mtcars))
```

```{r}
library(kableExtra)
```

```{r}
kable(head(mtcars))
```
````

**Comment by iago-pssjd** [comment] 2021-04-07 16:32
The code in the `Rmd` file is just this:

- - -
title: "Untitled"
output: html_document
- - -

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, results='asis')
library(knitr)
library(modelsummary)
```

```{r, results='asis'}
kable(mtcars)
data(trees)
models <- list()
models[['Bivariate']] <- lm(Girth ~ Height, data = trees)
models[['Multivariate']] <- lm(Girth ~ Height + Volume, data = trees)

# simple table
modelsummary(models, output = 'markdown')
kable(mtcars)

```

**Comment by iago-pssjd** [comment] 2021-04-07 16:34
Thanks!

**Comment by vincentarelbundock** [comment] 2021-04-09 11:38
Great news! Thanks for the useful follow up. Now I'll know what to tell people who run into the same problem.

**Comment by iago-pssjd** [comment] 2023-09-13 09:26
Hi! @vincentarelbundock,

Returning to your example:
````r
---
output: html_document
---

```{r}
library(knitr)
kable(head(mtcars))
```

```{r}
library(modelsummary)
mod = lm(hp ~ mpg, data = mtcars)
modelsummary(mod, output = "gt")
```

```{r}
kable(head(mtcars))
```
````

Actually, the second/last `kable` appears weird. Look its output at right below, against first `kable` output before loading `modelsummary` at left
![image](https://github.com/vincentarelbundock/modelsummary/assets/40892925/b7f48db4-7c20-45e9-add0-a7de110f9ef9)

As I told you in previous comments, for html documents I can solve this using th `kableExtra::kable_styling()` function. However, this function is not allowed when the Rmd output is a doc/word document, where a similar issue occurs, as you can see in the next screenshot. Again, the `kable` output before loading `modelsummary` is fine, while the output after is weird.

![image](https://github.com/vincentarelbundock/modelsummary/assets/40892925/4534395f-f2fe-4ba5-ba3f-ce64d5735640)

Therefore, I reopened the issue because I think this needs a solution.

**Comment by vincentarelbundock** [comment] 2023-09-13 10:55
kableExtra does not support word output, so none of its functions will work there.

**Comment by iago-pssjd** [comment] 2023-09-13 14:28
>  kableExtra does not support word output, so none of its functions will work there.

I meant that when I wrote

>  for html documents I can solve this using the `kableExtra::kable_styling()` function. However, this function is not allowed when the Rmd output is a doc/word document,

**Comment by vincentarelbundock** [comment] 2023-09-13 14:37
Try to call `knitr::kable()` instead of just `kable()`

**Comment by iago-pssjd** [comment] 2023-09-13 14:45
Nothing changes...

**Comment by vincentarelbundock** [comment] 2023-09-13 15:32
Well, Im sorry but I don't have a solution for you. The problem is not caused directly by modelsummary. It is caused by kableExtra.

The only solution I can imagine are:

Don't use kable() in your Word document. flextable has a very similar functionality, so you don't need kable for any of the simple examples you show here.

Alternatively, I could remove kableExtra as a dependency to modelsummary, but that comes with many problems, so I don't want to do that.

If you have other specific ideas, feel free to post below, but I'll be closing the issue now since I don't know what can be done.

**Closed** 2023-09-13 15:32 UTC

**Comment by iago-pssjd** [comment] 2023-09-13 15:44
> Don't use kable() in your Word document. flextable has a very similar functionality, so you don't need kable for any of the simple examples you show here.

I will check



> The problem is not caused directly by modelsummary. It is caused by kableExtra.

I only partially agree, since I do not use `kableExtra` for anything, neither directly nor through `modelsummary`, `output = "kableExtra"`. You say

> I could remove kableExtra as a dependency to modelsummary, but that comes with many problems, so I don't want to do that.

Ok, nothing to say.

**Comment by iago-pssjd** [comment] 2023-09-13 15:59
It seems that setting `options(kableExtra.auto_format = FALSE)` before loading `modelsummary` (in this case) solves the issue (https://github.com/haozhu233/kableExtra/issues/592)
