### ISSUE TITLE
Error when rendering datasummary_balance to Word

### ISSUE THREAD

**Issue by emilopezcano** [vincentarelbundock/modelsummary#367] opened 2021-08-18 22:10 UTC
The following chunk in an .Rmd file:

```
library(modelsummary)
datasummary_balance(formula = ~Species,
                    data = iris,
                    output = "flextable",
                    dinm = FALSE)
```

Produces an error when rendering to word_document. It does work running the chunk in the console, and also rendering to html or pdf. Apparently, the error is in the following line:

https://github.com/vincentarelbundock/modelsummary/blob/022f47bbb22048af672b5957210ffa90960bf963/R/datasummary_balance.R#L225

I think the reason could be that the first column of the table does not have a variable name (it is NULL). 

The error is also produced when using another output, e.g., "data.frame", so I could not find a solution at the time. 

Thank you very much

**Comment by emilopezcano** [comment] 2021-08-18 22:18
Update: It does work also when using as output `bookdown::word_document2`

**Comment by vincentarelbundock** [comment] 2021-08-19 03:33
Thanks for reporting this. This is to confirm that I can replicate the problem. I think I know what the issue is, but it might take me a little bit to implement a solution. Thanks for the report and for your patience.

**Comment by emilopezcano** [comment] 2021-08-19 06:04
Thank you for your work, looking forward to the solution.

**Comment by vincentarelbundock** [comment] 2021-08-20 00:21
When you have a second, could you please try the latest version from Github? (Make sure you restart R completely after install.)

With the new version you do NOT have to specify the output format. It should automatically pick `flextable` when the output is a Word document. That way, you don't have to change anything to produce a document that compiles to PDF, Word, or HTML.

**Comment by emilopezcano** [comment] 2021-08-20 06:23
I have installed the GitHub version and tested in my real environment (a shiny App that renders both html and word reports) and now everything works fine.

Thank you very much for having the solution so soon!

**Comment by vincentarelbundock** [comment] 2021-08-20 11:46
Fantastic!

I just released a new version and CRAN doesn't like back to back releases, so I have to wait for this a little. But the fix will be in the next official.

Thanks again for the report.

**Closed** 2021-08-20 11:46 UTC

**Comment by emilopezcano** [comment] 2021-08-20 12:53
Thank you!
