### ISSUE TITLE
new convenience function datasummary_xtab (or similar)

### ISSUE THREAD

**Issue by elbersb** [vincentarelbundock/modelsummary#276] opened 2021-04-29 11:07 UTC
As you know from Twitter, I'm a big fan of this package! 

Here's an idea: With `datasummary`, it's not so hard to generate crosstabs for categorical
variables and also add row/column sums, and row/column totals. One example is here:

``` r
library("modelsummary")
datasummary(Factor(cyl) * (N + Percent("row")) + 1 ~ Factor(gear) + 1, data = mtcars,
output = "markdown")
```

|     |         |     3 |     4 |     5 |    All |
|:----|:--------|------:|------:|------:|-------:|
| 4   | N       |     1 |     8 |     2 |     11 |
|     | Percent |  9.09 | 72.73 | 18.18 | 100.00 |
| 6   | N       |     2 |     4 |     1 |      7 |
|     | Percent | 28.57 | 57.14 | 14.29 | 100.00 |
| 8   | N       |    12 |     0 |     2 |     14 |
|     | Percent | 85.71 |  0.00 | 14.29 | 100.00 |
|     | All     | 15.00 | 12.00 |  5.00 |  32.00 |

<sup>Created on 2021-04-29 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

While this works, I think that a convenience function in the spirit of `datasummary_skim` could be useful here. This function could be called `datasummary_xtab` or `datasummary_crosstab` and have, for example, a signature like this:

```r
datasummary_xtab(var1, var2, N = True, cell = FALSE, row = FALSE, col = FALSE)
```

where the two first options specify the two variables to tabulate. `N` determines whether counts are shown, `cell` whether cell percentages are shown, and `row` and `col` whether row and column percentages are shown. This is somewhat inspired by Stata's `tabulate twoway` command. The function would in essence be a wrapper around `datasummary`, generating the correct formula given the options automatically.

If you think this would be worthwhile, I'd be happy to start working on a PR.

**Comment by vincentarelbundock** [comment] 2021-04-29 13:00
Hey @elbersb ! Thanks so much for your interest and for the interesting suggestion.

Overall, I'm quite open to the idea of including a `datasummary_crosstab` function. However, I really want to make sure that it fits the overall "design" of the package. So just to open the conversation, here are a few of the considerations that I have in mind when thinking about new functions:

1. *Argument number and consistency*. One of the main reasons I developed this package is that I grew exasperated with the 85+(!!) arguments in the main function of a competing regression table package. An overriding goal of `modelsummary` is to be absolutely ruthless in limiting the number of distinct arguments, both *within* functions and *across* them.
2. Relatedly, I'd like to make sure that arguments are as consistent from function to function as possible. In your proposed design, we would be introducing a bunch of new ones: `N`, `cell`, `row`, `col`, `var1`, `var2`.
3. The way I've been thinking about this is that the `datasummary_*` functions are ready-made templates that are more or less "fixed". They are mostly meant for quick interaction with the data. When people really want to customize their tables, they should learn straight `datasummary`.
4. To the extent possible, I'd love it if the `datasummary_*` functions could act as gateway drugs to the more powerful `datasummary`.

With all that in mind, I wonder if we couldn't think of a different user interface, perhaps with a formula that is closer to `datasummary`. For example, maybe we can think of something like this:

```r
datasummary_crosstab(
  cyl + 1 ~ gear + 1,
  data = mtcars)
```

All we would need to do internally would be to wrap both variables in `Factor` (or convert them internally before calling `datasummary`), and to do: `update(formula, "(N + Percent('row'))*.~.")`

Perhaps we can take this logic further and allow for nested/multi-level cross-tabs:

```r
datasummary_crosstab(
  am * cyl + 1 ~ gear + 1,
  data = mtcars)

datasummary_crosstab(
  cyl + 1 ~ am * gear + 1,
  data = mtcars)
```

I'm not sure what the best way of specifying percent or not, and row vs. columns. For instance, maybe some people will want percentages in parentheses instead like "37 (3%)" instead of in different cells.

Here again, I think the spirit should be that this should be a good looking template, with few customization options, and that if people want more, they can use `datasummary`. Perhaps we could help them do that by storing the formula in an attribute of the `datasummary_crosstab` output, so users can retrieve it, customize it, and feed it to `datasummary`.

Just brainstorming, here. Curious what you think about all this.

**Comment by vincentarelbundock** [comment] 2021-04-29 13:13
Minor point: one worry with the formula strategy I suggested is that by wrapping variables in `Function()` automagically, we might confuse users, since `datasummary` and `datasummary_crosstab` would behave differently with the same data. Perhaps there should be a warning issued if the variables in `datasummary_crosstab` are not already character or factors.

**Comment by elbersb** [comment] 2021-04-30 10:34
Hi Vincent! Thanks for the detailed response. I agree with most of your thoughts, and will just continue the brainstorming here.

What’s great about the `tab` function in Stata is that for each combination of the two categorical variables, you can show any combination of the count, the cell percentage, the row percentage, or the column percentage. So you could show all four below each other, or just the row percentage and the count, etc. I haven’t come with an elegant way to express this idea succinctly within *one* formula, but something like this signature would maybe be a good way forward:

```r
datasummary_crosstab(formula, stat = ~ N, data)
```

The `formula` is simply for specifying the variables to “cross” (perhaps even, as you suggested, with interactions). If any of the variables are numeric, they would be wrapped in `Factor()`, maybe with a warning. With `stat` you would specify the statistics to compute for each combination of the values of the two "crossed" variables, e.g.

```r
datasummary_crosstab(var1 ~ var2, stat = ~ N + Percent() + Percent("row") + Percent("Col"), data)
```

would display the count, the cell percentage and the row and column percentages for each combination. I would be in favor of including row and column totals by default. For more refined tables, such as where you want to combine all statistics into one cell (as you suggested), or if you want to suppress the totals, we would refer to `datasummary` instead.

Regarding your suggestion to store the formula for later use—I think that’s a great idea. One could even take this one step further (just spitballing here), by not having a function `datasummary_crosstab`, but a function `crosstab`, the only purpose of which is to generate a formula for use with `datasummary`. Example usage:

```r
form <- crosstab(var1 ~ var2, stat = ~ N + Percent() + Percent("row") + Percent("Col"))
# form is just a datasummary-compatible formula
datasummary(form, data)
```

This wouldn’t fit so well with the rest of the package though, unless the other functions work in a similar manner (i.e., datasummary_skim is superseded by a function skim that just returns a formula), e.g.

```r
datasummary(skim(.), data)
```

This is obviously a bit more radical, and I’m not even sure it’s feasible, but this interface might be a more general way to write custom “formula-generating” helper functions.

And a last, completely unrelated point: There is `msummary` as a short cut for `modelsummary`—`dsummary` as a shortcut for `datasummary` would be great to have as well!

**Comment by vincentarelbundock** [comment] 2021-04-30 12:19
Great, sounds like we're converging on something good.

1. I like the two formula design, but let's go with `statistic` instead of `stat`
2. OK for wrapping in Factor automatically and issuing a warning
3. What do you think of this as default? `statistic = 1 ~ 1 + N + Percent("row")`
4. It would be super cool if this formula worked as well: `var1 * var2 ~ var3` (and reverse too)
5. In principle, I like your idea for formula template extractors, but my intuition is that this is a rare programing pattern. I'm not sure it's worth going down that path for now.
6. Opening a new issue for `dsummary` shortcut.

**Comment by elbersb** [comment] 2021-04-30 13:31
> 1. I like the two formula design, but let's go with `statistic` instead of `stat`
> 2. OK for wrapping in Factor automatically and issuing a warning

+1

> 3. What do you think of this as default? `statistic = 1 ~ 1 + N + Percent("row")`

Just to clarify: So the first `1` would indicate row totals, and the second `1` would indicate column totals?

> 4. It would be super cool if this formula worked as well: `var1 * var2 ~ var3` (and reverse too)

Agreed!

**Comment by vincentarelbundock** [comment] 2021-04-30 13:33
> Just to clarify: So the first `1` would indicate row totals, and the second `1` would indicate column totals?

Yep, the point would be to stay consistent with `datasummary` syntax.

**Comment by elbersb** [comment] 2021-04-30 13:43
Yes, this is good. Ok, I'll take a stab at a first implementation soon, hopefully within the next two weeks.

**Comment by vincentarelbundock** [comment] 2021-04-30 13:46
Fantastic! My guess is that the tricky part will be to robustly combine the two formulas. Good luck and thanks for everything!

**Comment by vincentarelbundock** [comment] 2021-05-09 12:55
closed by https://github.com/vincentarelbundock/modelsummary/pull/284

**Closed by vincentarelbundock** 2021-05-09 12:55 UTC
Labels: enhancement
