### ISSUE TITLE
Under Appearance section.  Error msg in xml_children(x)[[search]]: subscript out of bounds.

### ISSUE THREAD

**Issue by rccline** [vincentarelbundock/modelsummary#414] opened 2021-11-16 23:10 UTC
Error in xml_children(x)[[search]] : subscript out of bounds

**reprex:** 

``` r
library(kableExtra)
library(modelsummary)
library(palmerpenguins)

datasummary(All(penguins) ~ sex * (Mean + SD),
            data = penguins,
            output = 'kableExtra') %>%
  row_spec(3, background = 'cyan', color = 'red')
#> Error in xml_children(x)[[search]]: subscript out of bounds
```

<sup>Created on 2021-11-16 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Code from Tutorial:**  
```r
library(kableExtra)
library(modelsummary)
library(palmerpenguins)

datasummary(All(penguins) ~ sex * (Mean + SD),
            data = penguins,
            output = 'kableExtra') %>%
  row_spec(3, background = 'cyan', color = 'red')
```

**Comment by vincentarelbundock** [comment] 2021-11-16 23:32
Thanks for the report!

I believe that this is a duplicate of https://github.com/vincentarelbundock/modelsummary/issues/395

If the solution in that issue does not resolve the problem, don't hesitate to ping me.

**Closed** 2021-11-16 23:54 UTC
Labels: bug
