### ISSUE TITLE
Stars are not calculated correctly.

### ISSUE THREAD

**Issue by julianlanger** [vincentarelbundock/modelsummary#264] opened 2021-04-15 15:45 UTC
I am currently trying to display fixest results using modelsummary. It seems that the stars are not calculated correctly when I pass robust standard errors as a list of named vectors through the vcov argument. The table displays the correct standard errors but the calculated stars seem wrong. For example, for a p-value of 0.0195 the table displays three stars. 

Is this an error or did you shift the threshold for the calculation of stars away from the usual convention? If so, is there a way of changing the thresholds?

**Comment by julianlanger** [comment] 2021-04-15 15:50
I found this in the modelsummary function. 

`#' * TRUE: *=.1, **=.05, ***=.01 `

This would indicate that there might be a rounding issue?

**Comment by julianlanger** [comment] 2021-04-15 15:57
When I analyze the output, it looks like modelsummary inserts the robust standard errors correctly but uses the normal standard errors to calculate stars.

**Comment by vincentarelbundock** [comment] 2021-04-15 16:12
Thanks for bringing this to my attention and for investigating!

Yes, that's right. The problem is that when people supply a named vector, `modelsummary` has no way to know if this vector represents standard errors, p values, t stats, or just some random emoji. It is a very general mechanism, but the generality of it means that `modelsummary` can't infer p values from standard errors.

I think the most principled way to change standard errors and p values and stars is to use a `tidy_custom.MODELCLASS` method, as described here:

https://vincentarelbundock.github.io/modelsummary/articles/modelsummary.html#customizing-existing-models-part-ii-

If your `tidy_custom` method returns a data.frame with 3 columns `term`, `std.error`, and `p.value`, then everything should work automatically, and the stars should be correct.

**Comment by julianlanger** [comment] 2021-04-15 18:23
Thank you for explaining it. For now, I fixed it by calculating the correct standard errors during estimation. Then, `modelsummary` automatically extracts the correct SEs and also computes the stars correctly.

**Comment by vincentarelbundock** [comment] 2021-04-15 18:40
Glad you found a solution!

I just improved the documentation to make the problem clearer to users.

Honestly, I can't think of a better user interface design at the moment. If you don't mind, I'll close the issue and reopen if a light bulb goes on.

**Closed by vincentarelbundock** 2021-04-15 18:40 UTC
Labels: bug

**Comment by pauschae** [comment] 2021-12-25 22:43
I think I also get the wrong stars, but with standard errors computed on estimation.
![image](https://user-images.githubusercontent.com/11628946/147394755-483d09ab-e9b2-4540-975b-9243db5d495a.png)

e.g. the bottom right one is wrong, should be 0 stars.

I also get negative p-values.
![image](https://user-images.githubusercontent.com/11628946/147394799-3871978b-b66c-4e8f-99a3-5f820648c091.png)

I use fixest::feols() for estimation.

modelsummary_0.9.4 fixest_0.10.1 

The putput of the fixest command looks fine. Thank you for the great package, besides this issue it looks like a huge improvement over what I've been using before.

**Comment by vincentarelbundock** [comment] 2021-12-26 13:15
@pauschae 

Could you please try again with the development versions of both `fixest` and `modelsummary`, installed from GitHub?

If it still does not work, could you give me reproducible code? Right now, I can't diagnose the problem because I don't know the actual code that you are using.

Is this really the same problem described in the post at the top of this issue? If so, did you understand my response about vectors?

**Comment by pauschae** [comment] 2021-12-26 19:31
> @pauschae
> 
> Could you please try again with the development versions of both `fixest` and `modelsummary`, installed from GitHub?

I used the development version of fixest. For modelsummary I get the following error, but the main package seemed to install fine.
Warning messages:
1: In i.p(...) :
  installation of package ‘systemfonts’ had non-zero exit status
2: In i.p(...) :
  installation of package ‘svglite’ had non-zero exit status
> 
> If it still does not work, could you give me reproducible code? Right now, I can't diagnose the problem because I don't know the actual code that you are using.

This reproduces some of the problems (I couldn't reproduce the negative p-values.)
fit 

![image](https://user-images.githubusercontent.com/11628946/147418208-55233900-b61d-439b-8d09-69f60fba3619.png)


modelsummary output
![image](https://user-images.githubusercontent.com/11628946/147417853-42f33851-040a-4209-b6d5-7fb5b233643d.png)


> Is this really the same problem described in the post at the top of this issue? If so, did you understand my response about vectors?

It looked the same initially, that's why I posted here, but I don't think so anymore, sorry.

**Comment by vincentarelbundock** [comment] 2021-12-26 19:33
Thanks, but I meant actually reproducible code, with real data, and the full commands you called for both fitting the model and drawing the table, with all the arguments of the `feols` and `modelsummary` functions that you used.

Without this, it's basically impossible for me to diagnose.

**Comment by pauschae** [comment] 2021-12-27 11:08
oh I am really sorry I forgot to copy and paste the code. 
`library("tidyverse")
library("fixest")
library("modelsummary")
set.seed(500)
df <- tibble(x = rnorm(10000000), y=rnorm(10000000), a = 0.5 *x,  z=rbinom(10000000, size = 100, prob = 0.5))
fit <- feols(a~y+x, vcov = "iid", data = df)
modelsummary(fit,
             estimate = "{estimate}{stars} ({std.error}, P = {p.value})")`

**Comment by vincentarelbundock** [comment] 2021-12-27 12:34
Thanks @pauschae!

I can reproduce your problem with version 0.9.4 of `modelsummary`.
However, the problem has been fixed in the development version.

My guess is that the warnings you see mean that the package was *not*
installed correctly. I recommend:

1.  Try installing the `svglite` and `systemfonts` packages manually
    with `installed.packages` to see what the problem is.
2.  Once you’ve successfully installed those packages, reinstall
    `modelsummary` from Github:
    `remotes::install_github("vincentarelbundock/modelsummary")`
3.  Restart your `R` session entirely.
4.  Call `library(modelsummary)` and `sessionInfo()` to make sure that
    version 0.9.4.9000 is loaded.

This is what I get with the latest version:

``` r
library("tibble")
library("fixest")
library("modelsummary")

set.seed(500)
df <- tibble(x = rnorm(10000000),
             y = rnorm(10000000),
             a = 0.5 * x,
             z = rbinom(10000000, size = 100, prob = 0.5))

fit <- feols(a ~ y + x, vcov = "iid", data = df)

summary(fit)
```

    ## OLS estimation, Dep. Var.: a
    ## Observations: 10,000,000 
    ## Standard-errors: IID 
    ##               Estimate Std. Error       t value  Pr(>|t|)    
    ## (Intercept) -6.780e-21   2.59e-20 -2.620120e-01   0.79331    
    ## y           -2.711e-20   2.59e-20 -1.048343e+00   0.29448    
    ## x            5.000e-01   2.59e-20  1.933178e+19 < 2.2e-16 ***
    ## ---
    ## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
    ## RMSE: 8.178e-17   Adj. R2: 1

``` r
modelsummary(
    fit,
    estimate = "{estimate}{stars} ({std.error}, P = {p.value})")
```

|             |            Model 1             |
| :---------- | :----------------------------: |
| (Intercept) |    0.000 (0.000, P = 0.793)    |
|             |            (0.000)             |
| y           |    0.000 (0.000, P = 0.294)    |
|             |            (0.000)             |
| x           | 0.500\*\*\* (0.000, P = 0.000) |
|             |            (0.000)             |
| Num.Obs.    |            10000000            |
| R2          |             1.000              |
| R2 Adj.     |             1.000              |
| R2 Within   |                                |
| R2 Pseudo   |                                |
| AIC         |         \-712470175.6          |
| BIC         |         \-712470133.2          |
| Log.Lik.    |         356235090.787          |
| Std.Errors  |              IID               |

``` r
sessionInfo()
```

    ## R version 4.1.2 (2021-11-01)
    ## Platform: x86_64-pc-linux-gnu (64-bit)
    ## Running under: Ubuntu 20.04.3 LTS
    ## 
    ## Matrix products: default
    ## BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.9.0
    ## LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.9.0
    ## 
    ## locale:
    ##  [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
    ##  [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
    ##  [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
    ##  [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
    ##  [9] LC_ADDRESS=C               LC_TELEPHONE=C            
    ## [11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       
    ## 
    ## attached base packages:
    ## [1] stats     graphics  grDevices utils     datasets  methods   base     
    ## 
    ## other attached packages:
    ## [1] modelsummary_0.9.4.9001 fixest_0.10.1           tibble_3.1.6           
    ## 
    ## loaded via a namespace (and not attached):
    ##  [1] zoo_1.8-9           tidyselect_1.1.1    xfun_0.29          
    ##  [4] purrr_0.3.4         lattice_0.20-45     colorspace_2.0-2   
    ##  [7] vctrs_0.3.8         generics_0.1.1      viridisLite_0.4.0  
    ## [10] htmltools_0.5.2     yaml_2.2.1          utf8_1.2.2         
    ## [13] rlang_0.4.12        pillar_1.6.4        glue_1.6.0         
    ## [16] DBI_1.1.1           lifecycle_1.0.1     stringr_1.4.0      
    ## [19] munsell_0.5.0       rvest_1.0.2         kableExtra_1.3.4   
    ## [22] evaluate_0.14       knitr_1.37          fastmap_1.1.0      
    ## [25] fansi_0.5.0         highr_0.9           broom_0.7.10       
    ## [28] Rcpp_1.0.7          backports_1.4.1     scales_1.1.1       
    ## [31] checkmate_2.0.0     webshot_0.5.2       systemfonts_1.0.3  
    ## [34] digest_0.6.29       stringi_1.7.6       dplyr_1.0.7        
    ## [37] numDeriv_2016.8-1.1 grid_4.1.2          tools_4.1.2        
    ## [40] sandwich_3.0-1      magrittr_2.0.1      Formula_1.2-4      
    ## [43] crayon_1.4.2        tidyr_1.1.4         pkgconfig_2.0.3    
    ## [46] ellipsis_0.3.2      dreamerr_1.2.3      xml2_1.3.3         
    ## [49] assertthat_0.2.1    rmarkdown_2.11      svglite_2.0.0      
    ## [52] httr_1.4.2          rstudioapi_0.13     R6_2.5.1           
    ## [55] tables_0.9.6        nlme_3.1-153        compiler_4.1.2

**Comment by vincentarelbundock** [comment] 2021-12-27 12:34
Thanks @pauschae!

I can reproduce your problem with version 0.9.4 of `modelsummary`.
However, the problem has been fixed in the development version.

My guess is that the warnings you see mean that the package was *not*
installed correctly. I recommend:

1.  Try installing the `svglite` and `systemfonts` packages manually
    with `installed.packages` to see what the problem is.
2.  Once you’ve successfully installed those packages, reinstall
    `modelsummary` from Github:
    `remotes::install_github("vincentarelbundock/modelsummary")`
3.  Restart your `R` session entirely.
4.  Call `library(modelsummary)` and `sessionInfo()` to make sure that
    version 0.9.4.9000 is loaded.

This is what I get with the latest version:

``` r
library("tibble")
library("fixest")
library("modelsummary")

set.seed(500)
df <- tibble(x = rnorm(10000000),
             y = rnorm(10000000),
             a = 0.5 * x,
             z = rbinom(10000000, size = 100, prob = 0.5))

fit <- feols(a ~ y + x, vcov = "iid", data = df)

summary(fit)
```

    ## OLS estimation, Dep. Var.: a
    ## Observations: 10,000,000 
    ## Standard-errors: IID 
    ##               Estimate Std. Error       t value  Pr(>|t|)    
    ## (Intercept) -6.780e-21   2.59e-20 -2.620120e-01   0.79331    
    ## y           -2.711e-20   2.59e-20 -1.048343e+00   0.29448    
    ## x            5.000e-01   2.59e-20  1.933178e+19 < 2.2e-16 ***
    ## ---
    ## Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
    ## RMSE: 8.178e-17   Adj. R2: 1

``` r
modelsummary(
    fit,
    estimate = "{estimate}{stars} ({std.error}, P = {p.value})")
```

|             |            Model 1             |
| :---------- | :----------------------------: |
| (Intercept) |    0.000 (0.000, P = 0.793)    |
|             |            (0.000)             |
| y           |    0.000 (0.000, P = 0.294)    |
|             |            (0.000)             |
| x           | 0.500\*\*\* (0.000, P = 0.000) |
|             |            (0.000)             |
| Num.Obs.    |            10000000            |
| R2          |             1.000              |
| R2 Adj.     |             1.000              |
| R2 Within   |                                |
| R2 Pseudo   |                                |
| AIC         |         \-712470175.6          |
| BIC         |         \-712470133.2          |
| Log.Lik.    |         356235090.787          |
| Std.Errors  |              IID               |

``` r
sessionInfo()
```

    ## R version 4.1.2 (2021-11-01)
    ## Platform: x86_64-pc-linux-gnu (64-bit)
    ## Running under: Ubuntu 20.04.3 LTS
    ## 
    ## Matrix products: default
    ## BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.9.0
    ## LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.9.0
    ## 
    ## locale:
    ##  [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
    ##  [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
    ##  [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
    ##  [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
    ##  [9] LC_ADDRESS=C               LC_TELEPHONE=C            
    ## [11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       
    ## 
    ## attached base packages:
    ## [1] stats     graphics  grDevices utils     datasets  methods   base     
    ## 
    ## other attached packages:
    ## [1] modelsummary_0.9.4.9001 fixest_0.10.1           tibble_3.1.6           
    ## 
    ## loaded via a namespace (and not attached):
    ##  [1] zoo_1.8-9           tidyselect_1.1.1    xfun_0.29          
    ##  [4] purrr_0.3.4         lattice_0.20-45     colorspace_2.0-2   
    ##  [7] vctrs_0.3.8         generics_0.1.1      viridisLite_0.4.0  
    ## [10] htmltools_0.5.2     yaml_2.2.1          utf8_1.2.2         
    ## [13] rlang_0.4.12        pillar_1.6.4        glue_1.6.0         
    ## [16] DBI_1.1.1           lifecycle_1.0.1     stringr_1.4.0      
    ## [19] munsell_0.5.0       rvest_1.0.2         kableExtra_1.3.4   
    ## [22] evaluate_0.14       knitr_1.37          fastmap_1.1.0      
    ## [25] fansi_0.5.0         highr_0.9           broom_0.7.10       
    ## [28] Rcpp_1.0.7          backports_1.4.1     scales_1.1.1       
    ## [31] checkmate_2.0.0     webshot_0.5.2       systemfonts_1.0.3  
    ## [34] digest_0.6.29       stringi_1.7.6       dplyr_1.0.7        
    ## [37] numDeriv_2016.8-1.1 grid_4.1.2          tools_4.1.2        
    ## [40] sandwich_3.0-1      magrittr_2.0.1      Formula_1.2-4      
    ## [43] crayon_1.4.2        tidyr_1.1.4         pkgconfig_2.0.3    
    ## [46] ellipsis_0.3.2      dreamerr_1.2.3      xml2_1.3.3         
    ## [49] assertthat_0.2.1    rmarkdown_2.11      svglite_2.0.0      
    ## [52] httr_1.4.2          rstudioapi_0.13     R6_2.5.1           
    ## [55] tables_0.9.6        nlme_3.1-153        compiler_4.1.2

**Comment by pauschae** [comment] 2021-12-27 13:18
Thank you! It actually took updating my tidyverse package. Now the error is gone. Negative p-values are also gone.

**Comment by vincentarelbundock** [comment] 2023-06-29 16:28
What versions are you using?

**Comment by knrob** [comment] 2023-06-29 16:49
```
R version 4.2.1 (2022-06-23)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Big Sur 11.6.5

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.2/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] carData_3.0-5           modelsummary_1.4.1.9006 fixest_0.11.1          

loaded via a namespace (and not attached):
 [1] nlme_3.1-157         insight_0.19.3       webshot_0.5.3        httr_1.4.6          
 [5] dreamerr_1.2.3       numDeriv_2016.8-1.1  bslib_0.5.0          tools_4.2.1         
 [9] backports_1.4.1      utf8_1.2.3           R6_2.5.1             DT_0.28             
[13] colorspace_2.1-0     tidyselect_1.2.0     emmeans_1.8.1-1      compiler_4.2.1      
[17] performance_0.10.4.1 cli_3.6.1            rvest_1.0.3          flextable_0.7.2     
[21] xml2_1.3.3           officer_0.4.3        sandwich_3.0-2       sass_0.4.6          
[25] bayestestR_0.13.1.1  scales_1.2.1         checkmate_2.2.0      lmtest_0.9-40       
[29] mvtnorm_1.1-3        tables_0.9.17        systemfonts_1.0.4    stringr_1.5.0       
[33] digest_0.6.32        rmarkdown_2.22       svglite_2.1.1        base64enc_0.1-3     
[37] pkgconfig_2.0.3      htmltools_0.5.5      parallelly_1.34.0    fastmap_1.1.1       
[41] htmlwidgets_1.6.2    rlang_1.1.1          readxl_1.4.2         rstudioapi_0.14     
[45] jquerylib_0.1.4      generics_0.1.3       jsonlite_1.8.5       zoo_1.8-12          
[49] dplyr_1.1.2          zip_2.2.0            magrittr_2.0.3       kableExtra_1.3.4    
[53] Formula_1.2-5        parameters_0.21.1.2  Matrix_1.4-1         Rcpp_1.0.10         
[57] munsell_0.5.0        fansi_1.0.4          gdtools_0.2.4        lifecycle_1.0.3     
[61] stringi_1.7.12       multcomp_1.4-20      MASS_7.3-57          grid_4.2.1          
[65] parallel_4.2.1       listenv_0.9.0        lattice_0.20-45      splines_4.2.1       
[69] knitr_1.43           pillar_1.9.0         uuid_1.1-0           estimability_1.4.1  
[73] effectsize_0.7.0.5   future.apply_1.9.0   codetools_0.2-18     glue_1.6.2          
[77] evaluate_0.21        data.table_1.14.8    vctrs_0.6.3          cellranger_1.1.0    
[81] purrr_1.0.1          tidyr_1.3.0          future_1.32.0        datawizard_0.8.0.4  
[85] cachem_1.0.8         xfun_0.39            xtable_1.8-4         broom_1.0.3         
[89] coda_0.19-4          survival_3.3-1       viridisLite_0.4.2    tibble_3.2.1        
[93] globals_0.16.2       TH.data_1.1-1  
```
