### ISSUE TITLE
Switch to avg slope reporting in modelsummary vignette

### ISSUE THREAD

**Issue by grantmcdermott** [vincentarelbundock/modelsummary#809] opened 2024-09-05 16:33 UTC
Minor issue, but I think the group contrast examples starting [here](https://marginaleffects.com/vignettes/tables.html?q=modelsum#contrasts) are potentially confusing, since the tables are simply reporting the number of observations in each group rather than the slopes coefficients, which are almost certainly going to be of more interest for tabling output.

Maybe switch to `avg_comparisons`?

``` r
library(marginaleffects)
library(modelsummary)

dat <- mtcars
dat$gear <- as.factor(dat$gear)
mod <- glm(vs ~ gear + mpg, data = dat, family = binomial)

cmp <- avg_comparisons(mod)
modelsummary(cmp, shape = term + contrast ~ model) 
```

<table style="width:57%;">
<colgroup>
<col style="width: 15%" />
<col style="width: 27%" />
<col style="width: 13%" />
</colgroup>
<thead>
<tr class="header">
<th></th>
<th></th>
<th><ol type="1">
<li></li>
</ol></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>gear</td>
<td>mean(4) - mean(3)</td>
<td>0.037</td>
</tr>
<tr class="even">
<td></td>
<td></td>
<td>(0.137)</td>
</tr>
<tr class="odd">
<td></td>
<td>mean(5) - mean(3)</td>
<td>-0.340</td>
</tr>
<tr class="even">
<td></td>
<td></td>
<td>(0.099)</td>
</tr>
<tr class="odd">
<td>mpg</td>
<td>mean(+1)</td>
<td>0.061</td>
</tr>
<tr class="even">
<td></td>
<td></td>
<td>(0.013)</td>
</tr>
<tr class="odd">
<td>Num.Obs.</td>
<td></td>
<td>32</td>
</tr>
<tr class="even">
<td>AIC</td>
<td></td>
<td>26.2</td>
</tr>
<tr class="odd">
<td>BIC</td>
<td></td>
<td>32.1</td>
</tr>
<tr class="even">
<td>Log.Lik.</td>
<td></td>
<td>-9.101</td>
</tr>
<tr class="odd">
<td>F</td>
<td></td>
<td>2.389</td>
</tr>
<tr class="even">
<td>RMSE</td>
<td></td>
<td>0.31</td>
</tr>
</tbody>
</table>

<sup>Created on 2024-09-05 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

**Comment by vincentarelbundock** [comment] 2024-09-05 16:39
I would call these group contrasts "counterfactual comparisons." For example, `mean(4)-mean(3)` is computed by:

1. Copying the entire 32 observations, and setting `gear` to 4
2. Copying the entire 32 observations, and setting `gear` to 3
3. Computing predictions in both sets
4. Taking the average difference between those predictions

So each contrast actually uses all 32 observations, which makes me feel like the "Num.Obs." row makes sense.

If you want to compute differences between subgroup average predictions, I'd do something like:

```r
avg_predictions(mod, by = "gear", hypothesis = ~ sequential)
```

**Comment by grantmcdermott** [comment] 2024-09-05 17:04
(Ugh, I just realised that I raised this in the wrong repo; should be in `marginaleffects`. Rushing too much this morning. Sorry!)

Cool, cool. Happy to close, but I will just say that reporting grouped avg_slopes/comparisons is one of the canonical use-cases of `marginaleffects`+`modelsummaary` IMO, since we are often interested in the modulating effect across groups. I think the docs do an excellent job demonstrating this elsewhere; it would be nice to see an example of it in the dedicated "Presentation tables" vignette. (I was motivated to raise this issue after helping a colleague that was stuck trying to do this.)

**Comment by vincentarelbundock** [comment] 2024-11-06 23:38
Alright, I looked into this a bit. Unfortunately, will have to close. The problem is that this would require considerable changes to *both* `marginaleffects` and `modelsummary` code bases. First, to keep track of group sizes, which we don't currently do in `marginaleffects`. Second, some special purpose code in `modelsummary` to retrieve those and add them to the bottom of the table, a job that is currently out-sourced to the `performance` package.

In general, I try to avoid building model-specific or feature-specific stuff in either packages, and this would require new code in *both* packages handle a very specific use-case.

So on balance, closing. Sorry to disappoint.

Of course, it's pretty easy to add new info semi-manually in `modelsummary`, but that's probably something you do only before sharing the "final" table.

**Closed by vincentarelbundock** 2024-11-06 23:38 UTC

**Comment by grantmcdermott** [comment] 2024-11-07 00:54
Thanks, but I think we might be talking passed each other? My suggestion was simply to report the results from `avg_comparisons` [here](https://marginaleffects.com/bonus/tables.html#contrasts) rather than `contrasts`. It was a small pedagogic suggestion rather than a big refactor one... probably confused by me raising in the wrong repo :-/

**Comment by vincentarelbundock** [comment] 2024-11-07 01:37
Ahhh! I see. Sorry I misread.

Good call. yes, I 'll change that.
