### ISSUE TITLE
datasummary(All(dataset) ~ ..., data = dataset) doesn't work with tibbles

### ISSUE THREAD

**Issue by fschaffner** [vincentarelbundock/modelsummary#395] opened 2021-10-20 11:25 UTC
Hi @vincentarelbundock, thanks for creating and maintaining this great  package!

I noticed that `datasummary()` does not work with tibbles, only with data frames. Could this be fixed?

```{r}
library("modelsummary")
library("tidyverse")

# Works
datasummary(All(mtcars) ~ Min + Max + Mean + Median + SD,
            data = mtcars)

# Doesn't work
mtcars_tibble <- as_tibble(mtcars)
datasummary(All(mtcars_tibble) ~ Min + Max + Mean + Median + SD,
            data = mtcars_tibble)
```

**Comment by fschaffner** [comment] 2021-10-20 15:16
I tried both with the latest release and with the GitHub version (0.9.2.9000). 

The error message is: 

`Warning messages:
1: In min(x, na.rm = na.rm) :
  no non-missing arguments to min; returning Inf
2: In max(x, na.rm = na.rm) :
  no non-missing arguments to max; returning -Inf`

The generated output looks like this:

![Screenshot 2021-10-20 at 16 14 15](https://user-images.githubusercontent.com/30056330/138121288-9c97108a-e292-4e88-b119-c0e34b385b95.png)

**Comment by vincentarelbundock** [comment] 2021-10-20 16:24
Ah yes! This is a bug in the `All` functions which is supplied by the upstream package `tables`. I gave actually supplied a patch to the maintainer, and it has been merged, but maybe it has not been updated on CRAN yet.

Unfortunately, there is nothing else I can do here.

**Closed** 2022-04-06 18:22 UTC
Labels: bug, upstream

**Comment by psychelzh** [comment] 2023-06-02 13:34
Is this issue now solved? But when I use `All()` to tibbles, there is still a warning:

```bash
Warning message:
In datasummary(All(data) ~ Mean + SD, data = data) :
  The `All()` function does not accept tibbles. Please convert `data` to a `data.frame` before calling `datasummary`. A bugfix patch has been submitted upstream to the `tables` package.
```

**Comment by vincentarelbundock** [comment] 2023-06-02 13:41
Thanks a lot for notifying me @psychelzh . You are right: the problem is fixed and the warning is obsolete. I have removed it in version 1.4.1.9005 of `modelsummary` (available on Github now).
