### ISSUE TITLE
Allow multiple significance levels in modelplot, visualize with different thickness

### ISSUE THREAD

**Issue by turbanisch** [vincentarelbundock/modelsummary#311] opened 2021-05-19 09:06 UTC
I was wondering if it makes sense to allow multiple significance levels in `modelplot`, and visualize them by overlaying the corresponding pointrange-bars of different thickness (or transparency). Stata's `coefplot` command is what I am having in mind here: http://repec.sowi.unibe.ch/stata/coefplot/confidence-intervals.html
I will try to come up with an implementation myself!

**Comment by vincentarelbundock** [comment] 2021-05-19 14:00
This is a very interesting idea. I like those plots\!

But here are two things that come to mind:

1.  I really like that arguments are 100% consistent between functions, and I would prefer it if we could make sure that `modelsummary` and `modelplot` use `conf_level` in exactly the same way.
2.  I wonder if we might be reinventing the wheel a bit. The [frequentist uncertainty vignette of the `ggdist` package ](https://mjskay.github.io/ggdist/articles/freq-uncertainty-vis.html), for example, shows a bunch of ways to draw thekinds of plots you have in mind (and many other related ones). I worry that we'll duplicate all this code and produce an inferior product.

This leads me to wonder if there’s a way would could facilitate using `ggdist` or similar functions instead of redevelopping a duplicate of all those functions ourselves. I’m not sure we want to bring in `ggdist` as a strict dependency (maybe as an optional), but I’m sure it’s possible to make the process easier for users. For example, this brings us close to what you want, but it’s a bit convoluted (**Warning: this code requires the latest Github version of `modelsummary`**):

``` r
library(modelsummary)
library(distributional)
library(ggdist)
library(ggplot2)

models <- list(
  lm(hp ~ mpg, mtcars),
  lm(hp ~ mpg + drat, mtcars)
)
dat <- modelplot(models, draw = FALSE)
dfs <- sapply(models, function(x) get_gof(x)$df.residual)
dat$df <- ifelse(dat$model == "Model 1", dfs[1], dfs[2])

ggplot(dat, aes(y = term)) +
  stat_dist_interval(
    aes(dist = dist_student_t(
      df = df,
      mu = estimate,
      sigma = std.error
    ))
  ) +
  facet_wrap(~model)
```

![](https://i.imgur.com/oXj2nox.png)

<details style="margin-bottom:10px;">

<summary>Session info</summary>

``` r
sessioninfo::session_info()
#> Warning in system("timedatectl", intern = TRUE): running command 'timedatectl'
#> had status 1
#> ─ Session info ───────────────────────────────────────────────────────────────
#>  setting  value                       
#>  version  R version 4.1.0 (2021-05-18)
#>  os       Ubuntu 20.04.2 LTS          
#>  system   x86_64, linux-gnu           
#>  ui       X11                         
#>  language (EN)                        
#>  collate  C.UTF-8                     
#>  ctype    C.UTF-8                     
#>  tz       America/Toronto             
#>  date     2021-05-19                  
#> 
#> ─ Packages ───────────────────────────────────────────────────────────────────
#>  package        * version    date       lib source             
#>  backports        1.2.1      2020-12-09 [1] standard (@1.2.1)  
#>  broom            0.7.6      2021-04-05 [1] standard (@0.7.6)  
#>  checkmate        2.0.0      2020-02-06 [1] standard (@2.0.0)  
#>  cli              2.5.0      2021-04-26 [1] standard (@2.5.0)  
#>  colorspace       2.0-1      2021-05-04 [1] standard (@2.0-1)  
#>  crayon           1.4.1      2021-02-08 [1] standard (@1.4.1)  
#>  curl             4.3.1      2021-04-30 [1] standard (@4.3.1)  
#>  digest           0.6.27     2020-10-24 [1] standard (@0.6.27) 
#>  distributional * 0.2.2      2021-02-02 [1] standard (@0.2.2)  
#>  dplyr            1.0.6      2021-05-05 [1] standard (@1.0.6)  
#>  ellipsis         0.3.2      2021-04-29 [1] standard (@0.3.2)  
#>  evaluate         0.14       2019-05-28 [1] standard (@0.14)   
#>  fansi            0.4.2      2021-01-15 [1] standard (@0.4.2)  
#>  farver           2.1.0      2021-02-28 [1] standard (@2.1.0)  
#>  forcats          0.5.1      2021-01-27 [1] standard (@0.5.1)  
#>  fs               1.5.0      2020-07-31 [1] standard (@1.5.0)  
#>  generics         0.1.0      2020-10-31 [1] standard (@0.1.0)  
#>  ggdist         * 2.4.0      2021-01-04 [1] standard (@2.4.0)  
#>  ggplot2        * 3.3.3      2020-12-30 [1] standard (@3.3.3)  
#>  glue             1.4.2      2020-08-27 [1] standard (@1.4.2)  
#>  gtable           0.3.0      2019-03-25 [1] standard (@0.3.0)  
#>  highr            0.9        2021-04-16 [1] standard (@0.9)    
#>  htmltools        0.5.1.1    2021-01-22 [1] standard (@0.5.1.1)
#>  httr             1.4.2      2020-07-20 [1] standard (@1.4.2)  
#>  knitr            1.33       2021-04-24 [1] standard (@1.33)   
#>  labeling         0.4.2      2020-10-20 [1] standard (@0.4.2)  
#>  lifecycle        1.0.0      2021-02-15 [1] standard (@1.0.0)  
#>  magrittr         2.0.1      2020-11-17 [1] standard (@2.0.1)  
#>  mime             0.10       2021-02-13 [1] standard (@0.10)   
#>  modelsummary   * 0.7.0.9000 2021-05-19 [1] local              
#>  munsell          0.5.0      2018-06-12 [1] standard (@0.5.0)  
#>  pillar           1.6.1      2021-05-16 [1] standard (@1.6.1)  
#>  pkgconfig        2.0.3      2019-09-22 [1] standard (@2.0.3)  
#>  purrr            0.3.4      2020-04-17 [1] standard (@0.3.4)  
#>  R.cache          0.15.0     2021-04-30 [1] standard (@0.15.0) 
#>  R.methodsS3      1.8.1      2020-08-26 [1] standard (@1.8.1)  
#>  R.oo             1.24.0     2020-08-26 [1] standard (@1.24.0) 
#>  R.utils          2.10.1     2020-08-26 [1] standard (@2.10.1) 
#>  R6               2.5.0      2020-10-28 [1] standard (@2.5.0)  
#>  reprex           2.0.0      2021-04-02 [1] standard (@2.0.0)  
#>  rlang            0.4.11     2021-04-30 [1] standard (@0.4.11) 
#>  rmarkdown        2.8        2021-05-07 [1] standard (@2.8)    
#>  scales           1.1.1      2020-05-11 [1] standard (@1.1.1)  
#>  sessioninfo      1.1.1      2018-11-05 [1] standard (@1.1.1)  
#>  stringi          1.6.2      2021-05-17 [1] standard (@1.6.2)  
#>  stringr          1.4.0      2019-02-10 [1] standard (@1.4.0)  
#>  styler           1.4.1      2021-03-30 [1] standard (@1.4.1)  
#>  tables           0.9.6      2020-09-22 [1] standard (@0.9.6)  
#>  tibble           3.1.2      2021-05-16 [1] standard (@3.1.2)  
#>  tidyr            1.1.3      2021-03-03 [1] standard (@1.1.3)  
#>  tidyselect       1.1.1      2021-04-30 [1] standard (@1.1.1)  
#>  utf8             1.2.1      2021-03-12 [1] standard (@1.2.1)  
#>  vctrs            0.3.8      2021-04-29 [1] standard (@0.3.8)  
#>  viridisLite      0.4.0      2021-04-13 [1] standard (@0.4.0)  
#>  withr            2.4.2      2021-04-18 [1] standard (@2.4.2)  
#>  xfun             0.23       2021-05-15 [1] standard (@0.23)   
#>  xml2             1.3.2      2020-04-23 [1] standard (@1.3.2)  
#>  yaml             2.2.1      2020-02-01 [1] standard (@2.2.1)  
#> 
#> [1] /home/vincent/R/x86_64-pc-linux-gnu-library/4.1
#> [2] /usr/local/lib/R/site-library
#> [3] /usr/lib/R/site-library
#> [4] /usr/lib/R/library
```

</details>

**Comment by turbanisch** [comment] 2021-05-19 21:17
Thanks for pointing me to the `ggdist` package - I have to admit I was not even aware of it and I agree that it does everything I need for now. I adapted your code using `stat_dist_pointinterval` and "dodging" the models to get the look I am after. I also tried passing the confidence intervals produced by `modelplot` directly to a geom (`geom_pointinterval`) which I find more intuitive but gathering the confidence intervals for different levels is a major pain: 

```r
library(tidyverse)
library(modelsummary)
library(ggdist)

# fit models
models <- list(
  lm(hp ~ mpg, mtcars),
  lm(hp ~ mpg + drat, mtcars)
)

# gather confidence intervals for different confidence levels
df_95 <- modelplot(models, conf_level = 0.95, draw = FALSE) %>% 
  rename_with(.cols = starts_with("conf."), ~ str_c(.x, "0.95", sep = "_"))
df_90 <- modelplot(models, conf_level = 0.9, draw = FALSE) %>% 
  rename_with(.cols = starts_with("conf."), ~ str_c(.x, "0.9", sep = "_"))

df <- left_join(df_95, df_90)

df <- df %>% 
  pivot_longer(
    cols = starts_with("conf."),
    names_to = c("conf_type", ".width"),
    names_pattern = "(.*)_(.*)",
    values_to = "values"
  ) %>% 
  mutate(.width = as.numeric(.width)) %>% 
  pivot_wider(
    names_from = conf_type,
    values_from = values
  )

# plot coefficients and confidence intervals
df %>%
  ggplot(aes(y = term, x = estimate, xmin = conf.low, xmax = conf.high, color = model)) +
  ggdist::geom_pointinterval(position = "dodge")
```
So I guess that you are right in saying that there is no point in re-inventing the wheel or destroying the design philosophy of the entire package... Even though I wish I could point my Stata friends to this package and claim that it does everything they are used to ;) Thanks for taking the time!

**Comment by vincentarelbundock** [comment] 2021-05-20 00:23
Cool, thanks.

But I think it's possible to simplify your code considerably. Maybe it would be worth it to include an example in the vignette. Or maybe even a wrapper function to help with this. See for ex:

``` r
library(tidyverse)
library(modelsummary)
library(ggdist)

# fit
models <- list(
  lm(hp ~ mpg, mtcars),
  lm(hp ~ mpg + drat, mtcars))

# summarize
dat <- map(c(.8, .9, .95), function(x) {
    modelplot(models, conf_level = x, draw = FALSE) %>%
    mutate(.width = x)}) %>%
  bind_rows

# plot
ggplot(dat, aes(
  y = term, x = estimate,
  xmin = conf.low, xmax = conf.high,
  color = model)) +
  ggdist::geom_pointinterval(position = "dodge")
```

![](https://i.imgur.com/heFkJ4e.png)

<details style="margin-bottom:10px;">
<summary>
Session info
</summary>

``` r
sessioninfo::session_info()
#> ─ Session info ───────────────────────────────────────────────────────────────
#>  setting  value                                      
#>  version  R version 4.1.0 Patched (2021-05-18 r80324)
#>  os       macOS Big Sur 10.16                        
#>  system   x86_64, darwin17.0                         
#>  ui       X11                                        
#>  language (EN)                                       
#>  collate  en_US.UTF-8                                
#>  ctype    en_US.UTF-8                                
#>  tz       America/Toronto                            
#>  date     2021-05-19                                 
#> 
#> ─ Packages ───────────────────────────────────────────────────────────────────
#>  package        * version    date       lib
#>  assertthat       0.2.1      2019-03-21 [1]
#>  backports        1.2.0      2020-11-02 [1]
#>  broom            0.7.2      2020-10-20 [1]
#>  cellranger       1.1.0      2016-07-27 [1]
#>  checkmate        2.0.0      2020-02-06 [1]
#>  cli              2.5.0      2021-04-26 [1]
#>  colorspace       2.0-0      2020-11-11 [1]
#>  crayon           1.3.4      2017-09-16 [1]
#>  curl             4.3        2019-12-02 [1]
#>  DBI              1.1.0      2019-12-15 [1]
#>  dbplyr           2.0.0      2020-11-03 [1]
#>  digest           0.6.27     2020-10-24 [1]
#>  distributional   0.2.2      2021-02-02 [1]
#>  dplyr          * 1.0.2      2020-08-18 [1]
#>  ellipsis         0.3.1      2020-05-15 [1]
#>  evaluate         0.14       2019-05-28 [1]
#>  farver           2.0.3      2020-01-16 [1]
#>  forcats        * 0.5.0      2020-03-01 [1]
#>  fs               1.5.0      2020-07-31 [1]
#>  generics         0.1.0      2020-10-31 [1]
#>  ggdist         * 2.4.0      2021-01-04 [1]
#>  ggplot2        * 3.3.2      2020-06-19 [1]
#>  glue             1.4.2      2020-08-27 [1]
#>  gtable           0.3.0      2019-03-25 [1]
#>  haven            2.3.1      2020-06-01 [1]
#>  hms              0.5.3      2020-01-08 [1]
#>  htmltools        0.5.0      2020-06-16 [1]
#>  httr             1.4.2      2020-07-20 [1]
#>  jsonlite         1.7.1      2020-09-07 [1]
#>  knitr            1.30       2020-09-22 [1]
#>  labeling         0.4.2      2020-10-20 [1]
#>  languageserver * 0.3.8      2020-12-01 [1]
#>  lifecycle        0.2.0      2020-03-06 [1]
#>  lubridate        1.7.9.2    2020-11-13 [1]
#>  magrittr         2.0.1      2020-11-17 [1]
#>  mime             0.9        2020-02-04 [1]
#>  modelr           0.1.8      2020-05-19 [1]
#>  modelsummary   * 0.7.0.9000 2021-05-19 [1]
#>  munsell          0.5.0      2018-06-12 [1]
#>  pillar           1.4.7      2020-11-20 [1]
#>  pkgconfig        2.0.3      2019-09-22 [1]
#>  ps               1.4.0      2020-10-07 [1]
#>  purrr          * 0.3.4      2020-04-17 [1]
#>  R.cache          0.14.0     2019-12-06 [1]
#>  R.methodsS3      1.8.1      2020-08-26 [1]
#>  R.oo             1.24.0     2020-08-26 [1]
#>  R.utils          2.10.1     2020-08-26 [1]
#>  R6               2.5.0      2020-10-28 [1]
#>  Rcpp             1.0.5      2020-07-06 [1]
#>  readr          * 1.4.0      2020-10-05 [1]
#>  readxl           1.3.1      2019-03-13 [1]
#>  rematch2         2.1.2      2020-05-01 [1]
#>  reprex           2.0.0      2021-04-02 [1]
#>  rlang            0.4.9      2020-11-26 [1]
#>  rmarkdown        2.5        2020-10-21 [1]
#>  rstudioapi       0.13       2020-11-12 [1]
#>  rvest            0.3.6      2020-07-25 [1]
#>  scales           1.1.1      2020-05-11 [1]
#>  sessioninfo      1.1.1      2018-11-05 [1]
#>  stringi          1.5.3      2020-09-09 [1]
#>  stringr        * 1.4.0      2019-02-10 [1]
#>  styler           1.3.2      2020-02-23 [1]
#>  tables           0.9.6      2020-09-22 [1]
#>  tibble         * 3.0.4      2020-10-12 [1]
#>  tidyr          * 1.1.2      2020-08-27 [1]
#>  tidyselect       1.1.0      2020-05-11 [1]
#>  tidyverse      * 1.3.0      2019-11-21 [1]
#>  vctrs            0.3.5      2020-11-17 [1]
#>  withr            2.3.0      2020-09-22 [1]
#>  xfun             0.19       2020-10-30 [1]
#>  xml2             1.3.2      2020-04-23 [1]
#>  yaml             2.2.1      2020-02-01 [1]
#>  source                                          
#>  CRAN (R 4.1.0)                                  
#>  CRAN (R 4.1.0)                                  
#>  CRAN (R 4.1.0)                                  
#>  CRAN (R 4.1.0)                                  
#>  CRAN (R 4.1.0)                                  
#>  standard (@2.5.0)                               
#>  CRAN (R 4.1.0)                                  
#>  CRAN (R 4.1.0)                                  
#>  CRAN (R 4.1.0)                                  
#>  CRAN (R 4.1.0)                                  
#>  CRAN (R 4.1.0)                                  
#>  CRAN (R 4.1.0)                                  
#>  standard (@0.2.2)                               
#>  CRAN (R 4.1.0)                                  
#>  CRAN (R 4.1.0)                                  
#>  CRAN (R 4.1.0)                                  
#>  CRAN (R 4.1.0)                                  
#>  CRAN (R 4.1.0)                                  
#>  CRAN (R 4.1.0)                                  
#>  CRAN (R 4.1.0)                                  
#>  standard (@2.4.0)                               
#>  CRAN (R 4.1.0)                                  
#>  CRAN (R 4.1.0)                                  
#>  CRAN (R 4.1.0)                                  
#>  CRAN (R 4.1.0)                                  
#>  CRAN (R 4.1.0)                                  
#>  CRAN (R 4.1.0)                                  
#>  CRAN (R 4.1.0)                                  
#>  CRAN (R 4.1.0)                                  
#>  CRAN (R 4.1.0)                                  
#>  CRAN (R 4.1.0)                                  
#>  CRAN (R 4.1.0)                                  
#>  CRAN (R 4.1.0)                                  
#>  CRAN (R 4.1.0)                                  
#>  CRAN (R 4.1.0)                                  
#>  CRAN (R 4.1.0)                                  
#>  CRAN (R 4.1.0)                                  
#>  Github (vincentarelbundock/modelsummary@a91ed8d)
#>  CRAN (R 4.1.0)                                  
#>  CRAN (R 4.1.0)                                  
#>  CRAN (R 4.1.0)                                  
#>  CRAN (R 4.1.0)                                  
#>  CRAN (R 4.1.0)                                  
#>  CRAN (R 4.1.0)                                  
#>  CRAN (R 4.1.0)                                  
#>  CRAN (R 4.1.0)                                  
#>  CRAN (R 4.1.0)                                  
#>  CRAN (R 4.1.0)                                  
#>  CRAN (R 4.1.0)                                  
#>  CRAN (R 4.1.0)                                  
#>  CRAN (R 4.1.0)                                  
#>  CRAN (R 4.1.0)                                  
#>  standard (@2.0.0)                               
#>  CRAN (R 4.1.0)                                  
#>  CRAN (R 4.1.0)                                  
#>  CRAN (R 4.1.0)                                  
#>  CRAN (R 4.1.0)                                  
#>  CRAN (R 4.1.0)                                  
#>  CRAN (R 4.1.0)                                  
#>  CRAN (R 4.1.0)                                  
#>  CRAN (R 4.1.0)                                  
#>  CRAN (R 4.1.0)                                  
#>  CRAN (R 4.1.0)                                  
#>  CRAN (R 4.1.0)                                  
#>  CRAN (R 4.1.0)                                  
#>  CRAN (R 4.1.0)                                  
#>  CRAN (R 4.1.0)                                  
#>  CRAN (R 4.1.0)                                  
#>  CRAN (R 4.1.0)                                  
#>  CRAN (R 4.1.0)                                  
#>  CRAN (R 4.1.0)                                  
#>  CRAN (R 4.1.0)                                  
#> 
#> [1] /Library/Frameworks/R.framework/Versions/4.1/Resources/library
```

</details>

**Comment by turbanisch** [comment] 2021-05-20 08:46
You're right, and using `map_dfr` even saves another line. Having such succinct code makes it hard to even ask for a wrapper function but that is of course your decision as the package creator. I personally would enjoy a pointer to the `ggdist` package or a worked example like this in the vignette but I am not certain how many people would actually find this helpful.

**Comment by vincentarelbundock** [comment] 2021-05-20 12:26
Good call on `map_dfr`

I added a reference and example to the vignette. Will close this now. Feel free to re-open this or another issue if you have more ideas/suggestions.

**Closed by vincentarelbundock** 2021-05-20 12:26 UTC
Labels: enhancement
