### ISSUE TITLE
GOF on the right-side when `shape = model ~ ...`

### ISSUE THREAD

**Issue by pmavros** [vincentarelbundock/modelsummary#620] opened 2023-04-07 10:18 UTC
Hi Vincent, 

Thanks for the amazing package.

I am trying to bundle 4 models (in long format). I want to have statistics (SE, p, etc) as columns) _and_ keep the g.o.f. metrics for each model. 

When i use shape = model + term ~ statistic (using formated statistic) it does not print the gof.

Is this a bug?

**Comment by vincentarelbundock** [comment] 2023-04-07 11:03
Can you supply a minimal reproducible example using public data like `mtcars`

**Comment by pmavros** [comment] 2023-04-07 11:15
thanks! I think this one reproduces the issue on my side at least.

```{r}
data(mtcars)
mtcars

models <- list(
  mpg = lm(mpg~cyl + disp, mtcars), 
  hp = lm(hp ~ cyl + disp, mtcars)
)

models

# here we can't suppress the statistic and keep everything in a single line  
modelsummary(models,
             statistic = NULL,
             estimate = "{estimate}{stars} [{conf.low}, {conf.high}] ",
             shape = "rbind",
             gof_map = c("nobs", "r2.squared")
)

# here we loose the gof
modelsummary(models,
             statistic = c("{std.error}","[{conf.low}, {conf.high}]", "statistic", "p.value"),
             estimate = "{estimate}{stars}",
             shape = model + term ~ statistic,                          
             gof_map = c("nobs", "r2.squared")
)
```

**Comment by vincentarelbundock** [comment] 2023-04-08 12:05
Thanks a lot for the report\!

The first case is clearly a bug, and I pushed a commit to Github to fix it. With version 1.3.0.9016 you can do this:

``` r
library(modelsummary)
models <- list(
  mpg = lm(mpg ~ cyl + disp, mtcars),
  hp = lm(hp ~ cyl + disp, mtcars))
modelsummary(models,
  statistic = NULL,
  estimate = "{estimate}{stars} [{conf.low}, {conf.high}] ",
  shape = "rcollapse",
  gof_map = c("nobs", "r.squared"))
```

|             |                             (1) |
| :---------- | ------------------------------: |
| (Intercept) | 34.661\*\*\* \[29.452, 39.870\] |
| cyl         |    \-1.587\* \[-3.043, -0.131\] |
| disp        |      \-0.021+ \[-0.042, 0.000\] |
| R2          |                           0.760 |
| (Intercept) |    \-32.432 \[-98.452, 33.589\] |
| cyl         |      24.515\* \[6.063, 42.966\] |
| disp        |         0.119 \[-0.147, 0.385\] |
| R2          |                           0.702 |
| :————       |                      —————————: |
| Num.Obs.    |                              32 |

``` r

packageVersion("modelsummary")
# [1] '1.3.0.9016'
```

The second case is less obviously a problem. The issue is that `model` is on the left-hand side of the shape formula, which orders them along rows. So we can’t just paste goodness-of-fit statistics at the BOTTOM of the table, because they wouldn’t match models. One option would be to put them on the right side of the table, but that would make super wide tables, and I don’t really like that.

**Comment by pmavros** [comment] 2023-04-18 07:19
Hi Vincent, 

Thanks for this update. I see your point on have the gof on the side. In my case there is still some value in having that flexibility (i ony want to report n_obs and r2 marg/conditional. on the side. We have many models, with different terms and we want to 'package' them neatly in 1-2 tables (with sub-groups for each model) instead of having separate 16 tables in a paper. Showing each model vertically does not work, because the terms change and it leads to very long tables (also not readable), hence I am playing around the stacked logic.

**Comment by vincentarelbundock** [comment] 2023-04-18 11:09
Got it. Makes sense.

For boring technical reasons, this would be a bit annoying to implement, and I am overworked at the moment. I'm going to leave this issue open as a reminder, but I can't promise a solution in the short or medium term.

In the meantime, you can always use the `add_columns` argument. It's a more manual process, but it should work.

**Comment by vincentarelbundock** [comment] 2024-03-11 01:51
It's been a while and haven't had the impulse. I'm probably not going to do this so closing now.

As stated above, `add_columns` provides a rather easy way to do this. sorry to disappoint.

**Closed by vincentarelbundock** 2024-03-11 01:51 UTC
