### ISSUE TITLE
Graphics API version mismatch in `datasummary_skim`

### ISSUE THREAD

**Issue by sammo3182** [vincentarelbundock/modelsummary#381] opened 2021-09-25 01:50 UTC
I'm a fan of using `datasummary_skim`, but today when using the function (to build a xaringan slide), the following error jumped out, and I can't figure out how to solve it with some research on online sources. I've already installed the deve version of `modelsummary` from github. Here're two examples:

```{r}
library(modelsummary)
datasummary_skim(mtcars)
```

```
Error in svglite_(filename, bg, width, height, pointsize, standalone,  : 
  Graphics API version mismatch
 Error in base::try(coord_radar, silent = TRUE) : 
object 'coord_radar' not found
14.
svglite_(filename, bg, width, height, pointsize, standalone, 
aliases, web_fonts, id, fix_text_size, scaling, always_valid)
13.
(function (filename = "Rplot%03d.svg", width = 10, height = 8, 
bg = "white", pointsize = 12, standalone = TRUE, system_fonts = list(), 
user_fonts = list(), web_fonts = list(), id = NULL, fix_text_size = TRUE, 
scaling = 1, always_valid = FALSE, file) ...
12.
do.call(dev, dots)
11.
graphics_dev(filename = file, dev = file_type, width = width, 
height = height, res = res, bg = "transparent")
10.
(function (x, width = 200, height = 50, res = 300, breaks = "Sturges", 
same_lim = TRUE, lim = NULL, xaxt = "n", yaxt = "n", ann = FALSE, 
col = "lightgray", border = NULL, dir = if (is_latex()) rmd_files_dir() else tempdir(), 
file = NULL, file_type = if (is_latex()) "pdf" else svglite::svglite, ...
9.
mapply(FUN = f, ..., SIMPLIFY = FALSE)
8.
(function (f, ...) 
{
f <- match.fun(f)
mapply(FUN = f, ..., SIMPLIFY = FALSE) ...
7.
do.call(Map, c(list(f = spec_hist), dots))
6.
kableExtra::spec_hist(histogram_list, col = "black", same_lim = FALSE)
5.
ensure_len_html(image, nrows, "image")
4.
column_spec_html(kable_input, column, width, bold, italic, monospace, 
underline, strikeout, color, background, border_left, border_right, 
width_min, width_max, extra_css, include_thead, link, new_tab, 
tooltip, popover, image)
3.
kableExtra::column_spec(out, column = 9, image = kableExtra::spec_hist(histogram_list, 
col = "black", same_lim = FALSE))
2.
datasummary_skim_numeric(data, output = output, fmt = fmt, histogram = histogram, 
title = title, notes = notes, align = align, escape = escape, 
...)
1.
datasummary_skim(mtcars)

```

```{r}
datasummary_skim(mtcars, output = "kableExtra")
```

```
Error in svglite_(filename, bg, width, height, pointsize, standalone, : 
Graphics API version mismatch
14.
svglite_(filename, bg, width, height, pointsize, standalone, 
aliases, web_fonts, id, fix_text_size, scaling, always_valid)
13.
(function (filename = "Rplot%03d.svg", width = 10, height = 8, 
bg = "white", pointsize = 12, standalone = TRUE, system_fonts = list(), 
user_fonts = list(), web_fonts = list(), id = NULL, fix_text_size = TRUE, 
scaling = 1, always_valid = FALSE, file) ...
12.
do.call(dev, dots)
11.
graphics_dev(filename = file, dev = file_type, width = width, 
height = height, res = res, bg = "transparent")
10.
(function (x, width = 200, height = 50, res = 300, breaks = "Sturges", 
same_lim = TRUE, lim = NULL, xaxt = "n", yaxt = "n", ann = FALSE, 
col = "lightgray", border = NULL, dir = if (is_latex()) rmd_files_dir() else tempdir(), 
file = NULL, file_type = if (is_latex()) "pdf" else svglite::svglite, ...
9.
mapply(FUN = f, ..., SIMPLIFY = FALSE)
8.
(function (f, ...) 
{
f <- match.fun(f)
mapply(FUN = f, ..., SIMPLIFY = FALSE) ...
7.
do.call(Map, c(list(f = spec_hist), dots))
6.
kableExtra::spec_hist(histogram_list, col = "black", same_lim = FALSE)
5.
ensure_len_html(image, nrows, "image")
4.
column_spec_html(kable_input, column, width, bold, italic, monospace, 
underline, strikeout, color, background, border_left, border_right, 
width_min, width_max, extra_css, include_thead, link, new_tab, 
tooltip, popover, image)
3.
kableExtra::column_spec(out, column = 9, image = kableExtra::spec_hist(histogram_list, 
col = "black", same_lim = FALSE))
2.
datasummary_skim_numeric(data, output = output, fmt = fmt, histogram = histogram, 
title = title, notes = notes, align = align, escape = escape, 
...)
1.
datasummary_skim(mtcars, output = "kableExtra")
```

```
> sessionInfo()
R Under development (unstable) (2021-05-17 r80314)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 19043)

Matrix products: default

locale:
[1] LC_COLLATE=English_United States.1252 
[2] LC_CTYPE=English_United States.1252   
[3] LC_MONETARY=English_United States.1252
[4] LC_NUMERIC=C                          
[5] LC_TIME=English_United States.1252    
system code page: 65001

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods  
[7] base     

other attached packages:
 [1] forcats_0.5.1           dplyr_1.0.7            
 [3] readr_2.0.1             tibble_3.1.4           
 [5] tidyverse_1.3.1         tidyr_1.1.3            
 [7] broom_0.7.9             purrr_0.3.4            
 [9] haven_2.4.3             stringr_1.4.0.9000     
[11] modelsummary_0.9.1.9000 interplot_0.2.9999     
[13] arm_1.11-2              lme4_1.1-27.1          
[15] Matrix_1.3-4            MASS_7.3-54            
[17] abind_1.4-5             dotwhisker_0.7.4       
[19] ggplot2_3.3.5.9000      RColorBrewer_1.1-2     
[21] xaringanExtra_0.2.4     icons_0.2.0            
[23] knitr_1.34              pacman_0.5.1           

loaded via a namespace (and not attached):
  [1] TH.data_1.0-10      minqa_1.2.4         colorspace_2.0-2   
  [4] ellipsis_0.3.2      estimability_1.3    ggstance_0.3.5     
  [7] flextable_0.6.8     htmlTable_2.2.1     fs_1.5.0           
 [10] parameters_0.14.0   base64enc_0.1-3     rstudioapi_0.13    
 [13] lubridate_1.7.10    fansi_0.5.0         mvtnorm_1.1-2      
 [16] xml2_1.3.2          codetools_0.2-18    splines_4.2.0      
 [19] jsonlite_1.7.2      Formula_1.2-4       nloptr_1.2.2.2     
 [22] interactionTest_1.2 cluster_2.1.2       dbplyr_2.1.1       
 [25] png_0.1-7           httr_1.4.2          compiler_4.2.0     
 [28] emmeans_1.6.3       backports_1.2.1     assertthat_0.2.1   
 [31] fastmap_1.1.0       cli_3.0.1           htmltools_0.5.2    
 [34] tools_4.2.0         coda_0.19-4         gtable_0.3.0       
 [37] glue_1.4.2          rappdirs_0.3.3      tables_0.9.6       
 [40] Rcpp_1.0.7          cellranger_1.1.0    vctrs_0.3.8        
 [43] svglite_2.0.0       nlme_3.1-153        insight_0.14.4     
 [46] xfun_0.26           rvest_1.0.1         lifecycle_1.0.1    
 [49] drhutools_0.1.0     zoo_1.8-9           scales_1.1.1       
 [52] hms_1.1.0           parallel_4.2.0      sandwich_3.0-1     
 [55] gridExtra_2.3       gdtools_0.2.3       rpart_4.1-15       
 [58] latticeExtra_0.6-29 stringi_1.7.4       bayestestR_0.11.0  
 [61] checkmate_2.0.0     boot_1.3-28         zip_2.2.0          
 [64] rlang_0.4.11        pkgconfig_2.0.3     systemfonts_1.0.2  
 [67] evaluate_0.14       lattice_0.20-45     htmlwidgets_1.5.4  
 [70] tidyselect_1.1.1    magrittr_2.0.1      R6_2.5.1           
 [73] generics_0.1.0      Hmisc_4.5-0         multcomp_1.4-17    
 [76] DBI_1.1.1           pillar_1.6.2        foreign_0.8-81     
 [79] withr_2.4.2         survival_3.2-13     datawizard_0.2.0.1 
 [82] nnet_7.3-16         modelr_0.1.8        crayon_1.4.1       
 [85] uuid_0.1-4          utf8_1.2.2          tzdb_0.1.2         
 [88] rmarkdown_2.11      officer_0.4.0       jpeg_0.1-9         
 [91] readxl_1.3.1        grid_4.2.0          data.table_1.14.0  
 [94] webshot_0.5.2       reprex_2.0.1        digest_0.6.28      
 [97] xtable_1.8-4        munsell_0.5.0       viridisLite_0.4.0  
[100] kableExtra_1.3.4  
```

**Comment by vincentarelbundock** [comment] 2021-09-25 02:04
Hi, thanks a lot for the bug report, I really appreciate it!

Unfortunately, I'm afraid there is nothing much I can do unless you provide a completely self-contained reproducible example. A *super* simple xaringan file or something like that. This website gives good hints about creating examples that will be most useful for developers: https://reprex.tidyverse.org/articles/reprex-dos-and-donts.html

I have never seen this error, so I wont' be able to diagnose otherwise.

**Comment by vincentarelbundock** [comment] 2021-09-25 11:19
Also, can your document include a basic `kableExtra` table with the `spec_hist` function? In other words, is this really a `modelsummary` problem, or rather a `kableExtra` problem?

See this section with a simple `kableExtra` example:

https://cran.r-project.org/web/packages/kableExtra/vignettes/awesome_table_in_html.html#Insert_Images_into_Columns

**Comment by sammo3182** [comment] 2021-09-26 23:33
I guess you are right, Vincent! It might be the problem of `kableExtra` , as shown in the following codes. I'll retweet the issue there.

``` r
library(modelsummary)
datasummary_skim(mtcars)
#> Error in svglite_(filename, bg, width, height, pointsize, standalone, : Graphics API version mismatch
kableExtra::spec_hist(knitr::kable(mtcars))
#> Error in svglite_(filename, bg, width, height, pointsize, standalone, : Graphics API version mismatch
```


> Also, can your document include a basic `kableExtra` table with the `spec_hist` function? In other words, is this really a `modelsummary` problem, or rather a `kableExtra` problem?
> 
> See this section with a simple `kableExtra` example:
> 
> https://cran.r-project.org/web/packages/kableExtra/vignettes/awesome_table_in_html.html#Insert_Images_into_Columns

**Comment by vincentarelbundock** [comment] 2021-09-26 23:35
Thanks for looking into this!

Since there is not much I can do about this on my end, I'll close the issue, but feel free to keep the discussion going if yout hink I can help.

**Closed by vincentarelbundock** 2021-09-26 23:35 UTC
Labels: bug, reproducible example needed

**Comment by sammo3182** [comment] 2021-09-26 23:42
Ha, I know what happened. It turns out reinstalling the `svglite` package fixed problem. I should figured that sooner, but there's no document for "svglite_" function making me lose the track of where the error came from. The issue might be created by the version update of R. For others who encounter the same problem, just run the following code:

```r
install.package(svglite)
```

**Comment by vincentarelbundock** [comment] 2021-09-26 23:43
Fantastic!
