### ISSUE TITLE
Model summary does not retrieve equation names from systems

### ISSUE THREAD

**Issue by mronkko** [vincentarelbundock/modelsummary#832] opened 2024-11-14 11:16 UTC
Test case:

```
library(systemfit)
library(modelsummary)

#### Exercise 5: Systems estimators  ####
# Generate data from the following model, N = 1000, seed 1234



N <- 1000
set.seed(1234)

x <- rnorm(N)
z <- .2*x + rnorm(N)
q <- rnorm(N)
p <- q + x + z + rnorm(N)
y1 <- 10 + x + z + q + 3*rnorm(N)
y2 <- 11.5 + x + z + q + 3*rnorm(N)
y3 <- 5 + p - 2*q + rnorm(N) 
y4 <- y3 + q + rnorm(N)

#Estimate the model using ols, 2sls, sure, and 3sls omitting the q variable. 
#Tabulate the results side by side. 

models <- list(p ~ x + z,
               y1 ~ x + z,
               y2 ~ x + z,
               y3 ~ p, 
               y4 ~ y3)

m1 <- systemfit(models, method = "OLS")
m2 <- systemfit(models, method = "2SLS", inst = ~ x + z)
m3 <- systemfit(models, method = "SUR")
m4 <- systemfit(models, method = "3SLS", inst = ~ x + z)

# Creating a model summary requires 
modelsummary(list(m1,), output = "markdown")
```

Produces 

```
+-------------+---------+
|             | (1)     |
+=============+=========+
| (Intercept) | 0.020   |
+-------------+---------+
|             | 0.945   |
+-------------+---------+
|             | 11.668  |
+-------------+---------+
|             | 4.937   |
+-------------+---------+
|             | 9.908   |
+-------------+---------+
|             | (0.045) |
+-------------+---------+
|             | (0.064) |
+-------------+---------+
|             | (0.098) |
+-------------+---------+
|             | (0.098) |
+-------------+---------+
|             | (0.099) |
+-------------+---------+
| x           | 0.886   |
+-------------+---------+
|             | 1.022   |
+-------------+---------+
|             | 1.094   |
+-------------+---------+
|             | (0.046) |
+-------------+---------+
|             | (0.101) |
+-------------+---------+
|             | (0.102) |
+-------------+---------+
| z           | 0.962   |
+-------------+---------+
|             | 0.964   |
+-------------+---------+
|             | 1.066   |
+-------------+---------+
|             | (0.046) |
+-------------+---------+
|             | (0.100) |
+-------------+---------+
|             | (0.100) |
+-------------+---------+
| p           | 0.558   |
+-------------+---------+
|             | (0.030) |
+-------------+---------+
| y3          | 0.824   |
+-------------+---------+
|             | (0.018) |
+-------------+---------+ 
```

The output does not identify which equation each intercept belongs to and also prints the standard errors after all intercepts instead of printing one under each.

**Comment by vincentarelbundock** [comment] 2024-11-14 11:48
Closing as duplicate of https://github.com/vincentarelbundock/modelsummary/issues/831

After you learn how to use the `shape` argument, if you find that the software is still not giving you what you want, please open a new issue with more description of the problem.

**Closed by vincentarelbundock** 2024-11-14 11:48 UTC
